// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/diegobermudez03/playhoot/game/session/workflows/sessionlifecycle (interfaces: createRepoAPI,joinRepoAPI,leaveRepoAPI,gameCurrentVersionReader,gamePinnedDefinitionReader)
//
// Generated by this command:
//
//	mockgen -package=sessionlifecycle -destination=mocks_test.go . createRepoAPI,joinRepoAPI,leaveRepoAPI,gameCurrentVersionReader,gamePinnedDefinitionReader
//

// Package sessionlifecycle is a generated GoMock package.
package sessionlifecycle

import (
	context "context"
	reflect "reflect"
	time "time"

	program "github.com/diegobermudez03/playhoot/game/language/v1/program"
	management "github.com/diegobermudez03/playhoot/game/management"
	repo "github.com/diegobermudez03/playhoot/game/session/workflows/sessionlifecycle/internal/repo"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockcreateRepoAPI is a mock of createRepoAPI interface.
type MockcreateRepoAPI struct {
	ctrl     *gomock.Controller
	recorder *MockcreateRepoAPIMockRecorder
	isgomock struct{}
}

// MockcreateRepoAPIMockRecorder is the mock recorder for MockcreateRepoAPI.
type MockcreateRepoAPIMockRecorder struct {
	mock *MockcreateRepoAPI
}

// NewMockcreateRepoAPI creates a new mock instance.
func NewMockcreateRepoAPI(ctrl *gomock.Controller) *MockcreateRepoAPI {
	mock := &MockcreateRepoAPI{ctrl: ctrl}
	mock.recorder = &MockcreateRepoAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcreateRepoAPI) EXPECT() *MockcreateRepoAPIMockRecorder {
	return m.recorder
}

// CreateJoinCode mocks base method.
func (m *MockcreateRepoAPI) CreateJoinCode(ctx context.Context, tx *gorm.DB, sessionID uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJoinCode", ctx, tx, sessionID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJoinCode indicates an expected call of CreateJoinCode.
func (mr *MockcreateRepoAPIMockRecorder) CreateJoinCode(ctx, tx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJoinCode", reflect.TypeOf((*MockcreateRepoAPI)(nil).CreateJoinCode), ctx, tx, sessionID)
}

// CreateSessionWithHost mocks base method.
func (m *MockcreateRepoAPI) CreateSessionWithHost(ctx context.Context, tx *gorm.DB, gameDefinitionUUID, hostUserUUID string, lobbyExpiresAt time.Time) (repo.CreatedSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSessionWithHost", ctx, tx, gameDefinitionUUID, hostUserUUID, lobbyExpiresAt)
	ret0, _ := ret[0].(repo.CreatedSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSessionWithHost indicates an expected call of CreateSessionWithHost.
func (mr *MockcreateRepoAPIMockRecorder) CreateSessionWithHost(ctx, tx, gameDefinitionUUID, hostUserUUID, lobbyExpiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSessionWithHost", reflect.TypeOf((*MockcreateRepoAPI)(nil).CreateSessionWithHost), ctx, tx, gameDefinitionUUID, hostUserUUID, lobbyExpiresAt)
}

// MockjoinRepoAPI is a mock of joinRepoAPI interface.
type MockjoinRepoAPI struct {
	ctrl     *gomock.Controller
	recorder *MockjoinRepoAPIMockRecorder
	isgomock struct{}
}

// MockjoinRepoAPIMockRecorder is the mock recorder for MockjoinRepoAPI.
type MockjoinRepoAPIMockRecorder struct {
	mock *MockjoinRepoAPI
}

// NewMockjoinRepoAPI creates a new mock instance.
func NewMockjoinRepoAPI(ctrl *gomock.Controller) *MockjoinRepoAPI {
	mock := &MockjoinRepoAPI{ctrl: ctrl}
	mock.recorder = &MockjoinRepoAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockjoinRepoAPI) EXPECT() *MockjoinRepoAPIMockRecorder {
	return m.recorder
}

// ActivateParticipant mocks base method.
func (m *MockjoinRepoAPI) ActivateParticipant(ctx context.Context, tx *gorm.DB, participantID uint, displayName string, joinedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateParticipant", ctx, tx, participantID, displayName, joinedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateParticipant indicates an expected call of ActivateParticipant.
func (mr *MockjoinRepoAPIMockRecorder) ActivateParticipant(ctx, tx, participantID, displayName, joinedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateParticipant", reflect.TypeOf((*MockjoinRepoAPI)(nil).ActivateParticipant), ctx, tx, participantID, displayName, joinedAt)
}

// CountActiveParticipants mocks base method.
func (m *MockjoinRepoAPI) CountActiveParticipants(ctx context.Context, tx *gorm.DB, sessionID uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveParticipants", ctx, tx, sessionID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveParticipants indicates an expected call of CountActiveParticipants.
func (mr *MockjoinRepoAPIMockRecorder) CountActiveParticipants(ctx, tx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveParticipants", reflect.TypeOf((*MockjoinRepoAPI)(nil).CountActiveParticipants), ctx, tx, sessionID)
}

// CreateActor mocks base method.
func (m *MockjoinRepoAPI) CreateActor(ctx context.Context, tx *gorm.DB, sessionID uint, userUUID string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActor", ctx, tx, sessionID, userUUID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateActor indicates an expected call of CreateActor.
func (mr *MockjoinRepoAPIMockRecorder) CreateActor(ctx, tx, sessionID, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActor", reflect.TypeOf((*MockjoinRepoAPI)(nil).CreateActor), ctx, tx, sessionID, userUUID)
}

// CreateParticipant mocks base method.
func (m *MockjoinRepoAPI) CreateParticipant(ctx context.Context, tx *gorm.DB, actorID uint, displayName string, joinedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateParticipant", ctx, tx, actorID, displayName, joinedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateParticipant indicates an expected call of CreateParticipant.
func (mr *MockjoinRepoAPIMockRecorder) CreateParticipant(ctx, tx, actorID, displayName, joinedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateParticipant", reflect.TypeOf((*MockjoinRepoAPI)(nil).CreateParticipant), ctx, tx, actorID, displayName, joinedAt)
}

// FindActor mocks base method.
func (m *MockjoinRepoAPI) FindActor(ctx context.Context, tx *gorm.DB, sessionID uint, userUUID string) (*repo.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActor", ctx, tx, sessionID, userUUID)
	ret0, _ := ret[0].(*repo.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActor indicates an expected call of FindActor.
func (mr *MockjoinRepoAPIMockRecorder) FindActor(ctx, tx, sessionID, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActor", reflect.TypeOf((*MockjoinRepoAPI)(nil).FindActor), ctx, tx, sessionID, userUUID)
}

// FindParticipant mocks base method.
func (m *MockjoinRepoAPI) FindParticipant(ctx context.Context, tx *gorm.DB, actorID uint) (*repo.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindParticipant", ctx, tx, actorID)
	ret0, _ := ret[0].(*repo.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindParticipant indicates an expected call of FindParticipant.
func (mr *MockjoinRepoAPIMockRecorder) FindParticipant(ctx, tx, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindParticipant", reflect.TypeOf((*MockjoinRepoAPI)(nil).FindParticipant), ctx, tx, actorID)
}

// ResolveSessionForJoinCode mocks base method.
func (m *MockjoinRepoAPI) ResolveSessionForJoinCode(ctx context.Context, joinCode uint) (*repo.JoinCodeResolution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveSessionForJoinCode", ctx, joinCode)
	ret0, _ := ret[0].(*repo.JoinCodeResolution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveSessionForJoinCode indicates an expected call of ResolveSessionForJoinCode.
func (mr *MockjoinRepoAPIMockRecorder) ResolveSessionForJoinCode(ctx, joinCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveSessionForJoinCode", reflect.TypeOf((*MockjoinRepoAPI)(nil).ResolveSessionForJoinCode), ctx, joinCode)
}

// RevokeActiveJoinCode mocks base method.
func (m *MockjoinRepoAPI) RevokeActiveJoinCode(ctx context.Context, tx *gorm.DB, sessionID uint, revokedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeActiveJoinCode", ctx, tx, sessionID, revokedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeActiveJoinCode indicates an expected call of RevokeActiveJoinCode.
func (mr *MockjoinRepoAPIMockRecorder) RevokeActiveJoinCode(ctx, tx, sessionID, revokedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeActiveJoinCode", reflect.TypeOf((*MockjoinRepoAPI)(nil).RevokeActiveJoinCode), ctx, tx, sessionID, revokedAt)
}

// SetSessionTerminal mocks base method.
func (m *MockjoinRepoAPI) SetSessionTerminal(ctx context.Context, tx *gorm.DB, sessionID uint, terminalAt time.Time, terminalReason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSessionTerminal", ctx, tx, sessionID, terminalAt, terminalReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSessionTerminal indicates an expected call of SetSessionTerminal.
func (mr *MockjoinRepoAPIMockRecorder) SetSessionTerminal(ctx, tx, sessionID, terminalAt, terminalReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionTerminal", reflect.TypeOf((*MockjoinRepoAPI)(nil).SetSessionTerminal), ctx, tx, sessionID, terminalAt, terminalReason)
}

// MockleaveRepoAPI is a mock of leaveRepoAPI interface.
type MockleaveRepoAPI struct {
	ctrl     *gomock.Controller
	recorder *MockleaveRepoAPIMockRecorder
	isgomock struct{}
}

// MockleaveRepoAPIMockRecorder is the mock recorder for MockleaveRepoAPI.
type MockleaveRepoAPIMockRecorder struct {
	mock *MockleaveRepoAPI
}

// NewMockleaveRepoAPI creates a new mock instance.
func NewMockleaveRepoAPI(ctrl *gomock.Controller) *MockleaveRepoAPI {
	mock := &MockleaveRepoAPI{ctrl: ctrl}
	mock.recorder = &MockleaveRepoAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockleaveRepoAPI) EXPECT() *MockleaveRepoAPIMockRecorder {
	return m.recorder
}

// DeactivateParticipant mocks base method.
func (m *MockleaveRepoAPI) DeactivateParticipant(ctx context.Context, tx *gorm.DB, participantID uint, leftAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateParticipant", ctx, tx, participantID, leftAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateParticipant indicates an expected call of DeactivateParticipant.
func (mr *MockleaveRepoAPIMockRecorder) DeactivateParticipant(ctx, tx, participantID, leftAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateParticipant", reflect.TypeOf((*MockleaveRepoAPI)(nil).DeactivateParticipant), ctx, tx, participantID, leftAt)
}

// FindActor mocks base method.
func (m *MockleaveRepoAPI) FindActor(ctx context.Context, tx *gorm.DB, sessionID uint, userUUID string) (*repo.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActor", ctx, tx, sessionID, userUUID)
	ret0, _ := ret[0].(*repo.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActor indicates an expected call of FindActor.
func (mr *MockleaveRepoAPIMockRecorder) FindActor(ctx, tx, sessionID, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActor", reflect.TypeOf((*MockleaveRepoAPI)(nil).FindActor), ctx, tx, sessionID, userUUID)
}

// FindParticipant mocks base method.
func (m *MockleaveRepoAPI) FindParticipant(ctx context.Context, tx *gorm.DB, actorID uint) (*repo.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindParticipant", ctx, tx, actorID)
	ret0, _ := ret[0].(*repo.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindParticipant indicates an expected call of FindParticipant.
func (mr *MockleaveRepoAPIMockRecorder) FindParticipant(ctx, tx, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindParticipant", reflect.TypeOf((*MockleaveRepoAPI)(nil).FindParticipant), ctx, tx, actorID)
}

// RevokeActiveJoinCode mocks base method.
func (m *MockleaveRepoAPI) RevokeActiveJoinCode(ctx context.Context, tx *gorm.DB, sessionID uint, revokedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeActiveJoinCode", ctx, tx, sessionID, revokedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeActiveJoinCode indicates an expected call of RevokeActiveJoinCode.
func (mr *MockleaveRepoAPIMockRecorder) RevokeActiveJoinCode(ctx, tx, sessionID, revokedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeActiveJoinCode", reflect.TypeOf((*MockleaveRepoAPI)(nil).RevokeActiveJoinCode), ctx, tx, sessionID, revokedAt)
}

// SetSessionTerminal mocks base method.
func (m *MockleaveRepoAPI) SetSessionTerminal(ctx context.Context, tx *gorm.DB, sessionID uint, terminalAt time.Time, terminalReason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSessionTerminal", ctx, tx, sessionID, terminalAt, terminalReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSessionTerminal indicates an expected call of SetSessionTerminal.
func (mr *MockleaveRepoAPIMockRecorder) SetSessionTerminal(ctx, tx, sessionID, terminalAt, terminalReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionTerminal", reflect.TypeOf((*MockleaveRepoAPI)(nil).SetSessionTerminal), ctx, tx, sessionID, terminalAt, terminalReason)
}

// MockgameCurrentVersionReader is a mock of gameCurrentVersionReader interface.
type MockgameCurrentVersionReader struct {
	ctrl     *gomock.Controller
	recorder *MockgameCurrentVersionReaderMockRecorder
	isgomock struct{}
}

// MockgameCurrentVersionReaderMockRecorder is the mock recorder for MockgameCurrentVersionReader.
type MockgameCurrentVersionReaderMockRecorder struct {
	mock *MockgameCurrentVersionReader
}

// NewMockgameCurrentVersionReader creates a new mock instance.
func NewMockgameCurrentVersionReader(ctrl *gomock.Controller) *MockgameCurrentVersionReader {
	mock := &MockgameCurrentVersionReader{ctrl: ctrl}
	mock.recorder = &MockgameCurrentVersionReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgameCurrentVersionReader) EXPECT() *MockgameCurrentVersionReaderMockRecorder {
	return m.recorder
}

// GetPlayableGameWithCurrentVersion mocks base method.
func (m *MockgameCurrentVersionReader) GetPlayableGameWithCurrentVersion(ctx context.Context, gameUUID string) (*management.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayableGameWithCurrentVersion", ctx, gameUUID)
	ret0, _ := ret[0].(*management.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayableGameWithCurrentVersion indicates an expected call of GetPlayableGameWithCurrentVersion.
func (mr *MockgameCurrentVersionReaderMockRecorder) GetPlayableGameWithCurrentVersion(ctx, gameUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayableGameWithCurrentVersion", reflect.TypeOf((*MockgameCurrentVersionReader)(nil).GetPlayableGameWithCurrentVersion), ctx, gameUUID)
}

// MockgamePinnedDefinitionReader is a mock of gamePinnedDefinitionReader interface.
type MockgamePinnedDefinitionReader struct {
	ctrl     *gomock.Controller
	recorder *MockgamePinnedDefinitionReaderMockRecorder
	isgomock struct{}
}

// MockgamePinnedDefinitionReaderMockRecorder is the mock recorder for MockgamePinnedDefinitionReader.
type MockgamePinnedDefinitionReaderMockRecorder struct {
	mock *MockgamePinnedDefinitionReader
}

// NewMockgamePinnedDefinitionReader creates a new mock instance.
func NewMockgamePinnedDefinitionReader(ctrl *gomock.Controller) *MockgamePinnedDefinitionReader {
	mock := &MockgamePinnedDefinitionReader{ctrl: ctrl}
	mock.recorder = &MockgamePinnedDefinitionReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgamePinnedDefinitionReader) EXPECT() *MockgamePinnedDefinitionReaderMockRecorder {
	return m.recorder
}

// GetGameDefinition mocks base method.
func (m *MockgamePinnedDefinitionReader) GetGameDefinition(ctx context.Context, gameDefinitionUUID string) (*program.Definition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameDefinition", ctx, gameDefinitionUUID)
	ret0, _ := ret[0].(*program.Definition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameDefinition indicates an expected call of GetGameDefinition.
func (mr *MockgamePinnedDefinitionReaderMockRecorder) GetGameDefinition(ctx, gameDefinitionUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameDefinition", reflect.TypeOf((*MockgamePinnedDefinitionReader)(nil).GetGameDefinition), ctx, gameDefinitionUUID)
}
