// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/diegobermudez03/playhoot/game/session/usecases/leavesession (interfaces: repoAPI)
//
// Generated by this command:
//
//	mockgen -package=leavesession -destination=repo_mock_test.go . repoAPI
//

// Package leavesession is a generated GoMock package.
package leavesession

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockrepoAPI is a mock of repoAPI interface.
type MockrepoAPI struct {
	ctrl     *gomock.Controller
	recorder *MockrepoAPIMockRecorder
	isgomock struct{}
}

// MockrepoAPIMockRecorder is the mock recorder for MockrepoAPI.
type MockrepoAPIMockRecorder struct {
	mock *MockrepoAPI
}

// NewMockrepoAPI creates a new mock instance.
func NewMockrepoAPI(ctrl *gomock.Controller) *MockrepoAPI {
	mock := &MockrepoAPI{ctrl: ctrl}
	mock.recorder = &MockrepoAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrepoAPI) EXPECT() *MockrepoAPIMockRecorder {
	return m.recorder
}

// leaveSession mocks base method.
func (m *MockrepoAPI) leaveSession(ctx context.Context, params leaveParams) (Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "leaveSession", ctx, params)
	ret0, _ := ret[0].(Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// leaveSession indicates an expected call of leaveSession.
func (mr *MockrepoAPIMockRecorder) leaveSession(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "leaveSession", reflect.TypeOf((*MockrepoAPI)(nil).leaveSession), ctx, params)
}
