// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/diegobermudez03/playhoot/session/workflows/sessionlifecycle (interfaces: createRepoAPI,joinRepoAPI,leaveRepoAPI,startRepoAPI,submitPlayerEventRepoAPI,expireTimerRepoAPI,cancelSessionRepoAPI)
//
// Generated by this command:
//
//	mockgen -package=sessionlifecycle -destination=mocks_test.go . createRepoAPI,joinRepoAPI,leaveRepoAPI,startRepoAPI,submitPlayerEventRepoAPI,expireTimerRepoAPI,cancelSessionRepoAPI
//

// Package sessionlifecycle is a generated GoMock package.
package sessionlifecycle

import (
	context "context"
	json "encoding/json"
	reflect "reflect"
	time "time"

	repo "github.com/diegobermudez03/playhoot/session/workflows/sessionlifecycle/internal/repo"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockcreateRepoAPI is a mock of createRepoAPI interface.
type MockcreateRepoAPI struct {
	ctrl     *gomock.Controller
	recorder *MockcreateRepoAPIMockRecorder
	isgomock struct{}
}

// MockcreateRepoAPIMockRecorder is the mock recorder for MockcreateRepoAPI.
type MockcreateRepoAPIMockRecorder struct {
	mock *MockcreateRepoAPI
}

// NewMockcreateRepoAPI creates a new mock instance.
func NewMockcreateRepoAPI(ctrl *gomock.Controller) *MockcreateRepoAPI {
	mock := &MockcreateRepoAPI{ctrl: ctrl}
	mock.recorder = &MockcreateRepoAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcreateRepoAPI) EXPECT() *MockcreateRepoAPIMockRecorder {
	return m.recorder
}

// ClaimSessionRequest mocks base method.
func (m *MockcreateRepoAPI) ClaimSessionRequest(ctx context.Context, tx *gorm.DB, input repo.ClaimSessionRequestInput) (uint, *repo.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimSessionRequest", ctx, tx, input)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(*repo.Request)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ClaimSessionRequest indicates an expected call of ClaimSessionRequest.
func (mr *MockcreateRepoAPIMockRecorder) ClaimSessionRequest(ctx, tx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimSessionRequest", reflect.TypeOf((*MockcreateRepoAPI)(nil).ClaimSessionRequest), ctx, tx, input)
}

// CompleteSessionRequest mocks base method.
func (m *MockcreateRepoAPI) CompleteSessionRequest(ctx context.Context, tx *gorm.DB, requestID uint, sessionID *uint, outcome, responsePayload string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteSessionRequest", ctx, tx, requestID, sessionID, outcome, responsePayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteSessionRequest indicates an expected call of CompleteSessionRequest.
func (mr *MockcreateRepoAPIMockRecorder) CompleteSessionRequest(ctx, tx, requestID, sessionID, outcome, responsePayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteSessionRequest", reflect.TypeOf((*MockcreateRepoAPI)(nil).CompleteSessionRequest), ctx, tx, requestID, sessionID, outcome, responsePayload)
}

// CreateJoinCode mocks base method.
func (m *MockcreateRepoAPI) CreateJoinCode(ctx context.Context, tx *gorm.DB, sessionID uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJoinCode", ctx, tx, sessionID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJoinCode indicates an expected call of CreateJoinCode.
func (mr *MockcreateRepoAPIMockRecorder) CreateJoinCode(ctx, tx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJoinCode", reflect.TypeOf((*MockcreateRepoAPI)(nil).CreateJoinCode), ctx, tx, sessionID)
}

// CreateSessionWithHost mocks base method.
func (m *MockcreateRepoAPI) CreateSessionWithHost(ctx context.Context, tx *gorm.DB, gameDefinitionUUID, hostUserUUID string, lobbyExpiresAt time.Time) (repo.CreatedSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSessionWithHost", ctx, tx, gameDefinitionUUID, hostUserUUID, lobbyExpiresAt)
	ret0, _ := ret[0].(repo.CreatedSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSessionWithHost indicates an expected call of CreateSessionWithHost.
func (mr *MockcreateRepoAPIMockRecorder) CreateSessionWithHost(ctx, tx, gameDefinitionUUID, hostUserUUID, lobbyExpiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSessionWithHost", reflect.TypeOf((*MockcreateRepoAPI)(nil).CreateSessionWithHost), ctx, tx, gameDefinitionUUID, hostUserUUID, lobbyExpiresAt)
}

// ResolveCurrentGameDefinitionUUID mocks base method.
func (m *MockcreateRepoAPI) ResolveCurrentGameDefinitionUUID(ctx context.Context, gameUUID string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveCurrentGameDefinitionUUID", ctx, gameUUID)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveCurrentGameDefinitionUUID indicates an expected call of ResolveCurrentGameDefinitionUUID.
func (mr *MockcreateRepoAPIMockRecorder) ResolveCurrentGameDefinitionUUID(ctx, gameUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveCurrentGameDefinitionUUID", reflect.TypeOf((*MockcreateRepoAPI)(nil).ResolveCurrentGameDefinitionUUID), ctx, gameUUID)
}

// MockjoinRepoAPI is a mock of joinRepoAPI interface.
type MockjoinRepoAPI struct {
	ctrl     *gomock.Controller
	recorder *MockjoinRepoAPIMockRecorder
	isgomock struct{}
}

// MockjoinRepoAPIMockRecorder is the mock recorder for MockjoinRepoAPI.
type MockjoinRepoAPIMockRecorder struct {
	mock *MockjoinRepoAPI
}

// NewMockjoinRepoAPI creates a new mock instance.
func NewMockjoinRepoAPI(ctrl *gomock.Controller) *MockjoinRepoAPI {
	mock := &MockjoinRepoAPI{ctrl: ctrl}
	mock.recorder = &MockjoinRepoAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockjoinRepoAPI) EXPECT() *MockjoinRepoAPIMockRecorder {
	return m.recorder
}

// ActivateParticipant mocks base method.
func (m *MockjoinRepoAPI) ActivateParticipant(ctx context.Context, tx *gorm.DB, participantID uint, displayName string, joinedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateParticipant", ctx, tx, participantID, displayName, joinedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateParticipant indicates an expected call of ActivateParticipant.
func (mr *MockjoinRepoAPIMockRecorder) ActivateParticipant(ctx, tx, participantID, displayName, joinedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateParticipant", reflect.TypeOf((*MockjoinRepoAPI)(nil).ActivateParticipant), ctx, tx, participantID, displayName, joinedAt)
}

// ClaimSessionRequest mocks base method.
func (m *MockjoinRepoAPI) ClaimSessionRequest(ctx context.Context, tx *gorm.DB, input repo.ClaimSessionRequestInput) (uint, *repo.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimSessionRequest", ctx, tx, input)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(*repo.Request)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ClaimSessionRequest indicates an expected call of ClaimSessionRequest.
func (mr *MockjoinRepoAPIMockRecorder) ClaimSessionRequest(ctx, tx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimSessionRequest", reflect.TypeOf((*MockjoinRepoAPI)(nil).ClaimSessionRequest), ctx, tx, input)
}

// CompleteSessionRequest mocks base method.
func (m *MockjoinRepoAPI) CompleteSessionRequest(ctx context.Context, tx *gorm.DB, requestID uint, sessionID *uint, outcome, responsePayload string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteSessionRequest", ctx, tx, requestID, sessionID, outcome, responsePayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteSessionRequest indicates an expected call of CompleteSessionRequest.
func (mr *MockjoinRepoAPIMockRecorder) CompleteSessionRequest(ctx, tx, requestID, sessionID, outcome, responsePayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteSessionRequest", reflect.TypeOf((*MockjoinRepoAPI)(nil).CompleteSessionRequest), ctx, tx, requestID, sessionID, outcome, responsePayload)
}

// CountActiveParticipants mocks base method.
func (m *MockjoinRepoAPI) CountActiveParticipants(ctx context.Context, tx *gorm.DB, sessionID uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveParticipants", ctx, tx, sessionID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveParticipants indicates an expected call of CountActiveParticipants.
func (mr *MockjoinRepoAPIMockRecorder) CountActiveParticipants(ctx, tx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveParticipants", reflect.TypeOf((*MockjoinRepoAPI)(nil).CountActiveParticipants), ctx, tx, sessionID)
}

// CreateActor mocks base method.
func (m *MockjoinRepoAPI) CreateActor(ctx context.Context, tx *gorm.DB, sessionID uint, userUUID string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActor", ctx, tx, sessionID, userUUID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateActor indicates an expected call of CreateActor.
func (mr *MockjoinRepoAPIMockRecorder) CreateActor(ctx, tx, sessionID, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActor", reflect.TypeOf((*MockjoinRepoAPI)(nil).CreateActor), ctx, tx, sessionID, userUUID)
}

// CreateParticipant mocks base method.
func (m *MockjoinRepoAPI) CreateParticipant(ctx context.Context, tx *gorm.DB, actorID uint, displayName string, joinedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateParticipant", ctx, tx, actorID, displayName, joinedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateParticipant indicates an expected call of CreateParticipant.
func (mr *MockjoinRepoAPIMockRecorder) CreateParticipant(ctx, tx, actorID, displayName, joinedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateParticipant", reflect.TypeOf((*MockjoinRepoAPI)(nil).CreateParticipant), ctx, tx, actorID, displayName, joinedAt)
}

// FindActor mocks base method.
func (m *MockjoinRepoAPI) FindActor(ctx context.Context, tx *gorm.DB, sessionID uint, userUUID string) (*repo.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActor", ctx, tx, sessionID, userUUID)
	ret0, _ := ret[0].(*repo.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActor indicates an expected call of FindActor.
func (mr *MockjoinRepoAPIMockRecorder) FindActor(ctx, tx, sessionID, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActor", reflect.TypeOf((*MockjoinRepoAPI)(nil).FindActor), ctx, tx, sessionID, userUUID)
}

// FindParticipant mocks base method.
func (m *MockjoinRepoAPI) FindParticipant(ctx context.Context, tx *gorm.DB, actorID uint) (*repo.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindParticipant", ctx, tx, actorID)
	ret0, _ := ret[0].(*repo.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindParticipant indicates an expected call of FindParticipant.
func (mr *MockjoinRepoAPIMockRecorder) FindParticipant(ctx, tx, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindParticipant", reflect.TypeOf((*MockjoinRepoAPI)(nil).FindParticipant), ctx, tx, actorID)
}

// LockSessionByID mocks base method.
func (m *MockjoinRepoAPI) LockSessionByID(ctx context.Context, tx *gorm.DB, sessionID uint) (*repo.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockSessionByID", ctx, tx, sessionID)
	ret0, _ := ret[0].(*repo.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockSessionByID indicates an expected call of LockSessionByID.
func (mr *MockjoinRepoAPIMockRecorder) LockSessionByID(ctx, tx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockSessionByID", reflect.TypeOf((*MockjoinRepoAPI)(nil).LockSessionByID), ctx, tx, sessionID)
}

// ResolveGameVersionArtifact mocks base method.
func (m *MockjoinRepoAPI) ResolveGameVersionArtifact(ctx context.Context, definitionUUID string) (*repo.GameVersionArtifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveGameVersionArtifact", ctx, definitionUUID)
	ret0, _ := ret[0].(*repo.GameVersionArtifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveGameVersionArtifact indicates an expected call of ResolveGameVersionArtifact.
func (mr *MockjoinRepoAPIMockRecorder) ResolveGameVersionArtifact(ctx, definitionUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveGameVersionArtifact", reflect.TypeOf((*MockjoinRepoAPI)(nil).ResolveGameVersionArtifact), ctx, definitionUUID)
}

// ResolveSessionForJoinCode mocks base method.
func (m *MockjoinRepoAPI) ResolveSessionForJoinCode(ctx context.Context, joinCode uint) (*repo.JoinCodeResolution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveSessionForJoinCode", ctx, joinCode)
	ret0, _ := ret[0].(*repo.JoinCodeResolution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveSessionForJoinCode indicates an expected call of ResolveSessionForJoinCode.
func (mr *MockjoinRepoAPIMockRecorder) ResolveSessionForJoinCode(ctx, joinCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveSessionForJoinCode", reflect.TypeOf((*MockjoinRepoAPI)(nil).ResolveSessionForJoinCode), ctx, joinCode)
}

// MockleaveRepoAPI is a mock of leaveRepoAPI interface.
type MockleaveRepoAPI struct {
	ctrl     *gomock.Controller
	recorder *MockleaveRepoAPIMockRecorder
	isgomock struct{}
}

// MockleaveRepoAPIMockRecorder is the mock recorder for MockleaveRepoAPI.
type MockleaveRepoAPIMockRecorder struct {
	mock *MockleaveRepoAPI
}

// NewMockleaveRepoAPI creates a new mock instance.
func NewMockleaveRepoAPI(ctrl *gomock.Controller) *MockleaveRepoAPI {
	mock := &MockleaveRepoAPI{ctrl: ctrl}
	mock.recorder = &MockleaveRepoAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockleaveRepoAPI) EXPECT() *MockleaveRepoAPIMockRecorder {
	return m.recorder
}

// ClaimSessionRequest mocks base method.
func (m *MockleaveRepoAPI) ClaimSessionRequest(ctx context.Context, tx *gorm.DB, input repo.ClaimSessionRequestInput) (uint, *repo.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimSessionRequest", ctx, tx, input)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(*repo.Request)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ClaimSessionRequest indicates an expected call of ClaimSessionRequest.
func (mr *MockleaveRepoAPIMockRecorder) ClaimSessionRequest(ctx, tx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimSessionRequest", reflect.TypeOf((*MockleaveRepoAPI)(nil).ClaimSessionRequest), ctx, tx, input)
}

// CompleteSessionRequest mocks base method.
func (m *MockleaveRepoAPI) CompleteSessionRequest(ctx context.Context, tx *gorm.DB, requestID uint, sessionID *uint, outcome, responsePayload string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteSessionRequest", ctx, tx, requestID, sessionID, outcome, responsePayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteSessionRequest indicates an expected call of CompleteSessionRequest.
func (mr *MockleaveRepoAPIMockRecorder) CompleteSessionRequest(ctx, tx, requestID, sessionID, outcome, responsePayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteSessionRequest", reflect.TypeOf((*MockleaveRepoAPI)(nil).CompleteSessionRequest), ctx, tx, requestID, sessionID, outcome, responsePayload)
}

// DeactivateParticipant mocks base method.
func (m *MockleaveRepoAPI) DeactivateParticipant(ctx context.Context, tx *gorm.DB, participantID uint, leftAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateParticipant", ctx, tx, participantID, leftAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateParticipant indicates an expected call of DeactivateParticipant.
func (mr *MockleaveRepoAPIMockRecorder) DeactivateParticipant(ctx, tx, participantID, leftAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateParticipant", reflect.TypeOf((*MockleaveRepoAPI)(nil).DeactivateParticipant), ctx, tx, participantID, leftAt)
}

// FindActor mocks base method.
func (m *MockleaveRepoAPI) FindActor(ctx context.Context, tx *gorm.DB, sessionID uint, userUUID string) (*repo.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActor", ctx, tx, sessionID, userUUID)
	ret0, _ := ret[0].(*repo.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActor indicates an expected call of FindActor.
func (mr *MockleaveRepoAPIMockRecorder) FindActor(ctx, tx, sessionID, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActor", reflect.TypeOf((*MockleaveRepoAPI)(nil).FindActor), ctx, tx, sessionID, userUUID)
}

// FindParticipant mocks base method.
func (m *MockleaveRepoAPI) FindParticipant(ctx context.Context, tx *gorm.DB, actorID uint) (*repo.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindParticipant", ctx, tx, actorID)
	ret0, _ := ret[0].(*repo.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindParticipant indicates an expected call of FindParticipant.
func (mr *MockleaveRepoAPIMockRecorder) FindParticipant(ctx, tx, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindParticipant", reflect.TypeOf((*MockleaveRepoAPI)(nil).FindParticipant), ctx, tx, actorID)
}

// LockSessionByUUID mocks base method.
func (m *MockleaveRepoAPI) LockSessionByUUID(ctx context.Context, tx *gorm.DB, sessionUUID string) (*repo.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockSessionByUUID", ctx, tx, sessionUUID)
	ret0, _ := ret[0].(*repo.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockSessionByUUID indicates an expected call of LockSessionByUUID.
func (mr *MockleaveRepoAPIMockRecorder) LockSessionByUUID(ctx, tx, sessionUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockSessionByUUID", reflect.TypeOf((*MockleaveRepoAPI)(nil).LockSessionByUUID), ctx, tx, sessionUUID)
}

// MockstartRepoAPI is a mock of startRepoAPI interface.
type MockstartRepoAPI struct {
	ctrl     *gomock.Controller
	recorder *MockstartRepoAPIMockRecorder
	isgomock struct{}
}

// MockstartRepoAPIMockRecorder is the mock recorder for MockstartRepoAPI.
type MockstartRepoAPIMockRecorder struct {
	mock *MockstartRepoAPI
}

// NewMockstartRepoAPI creates a new mock instance.
func NewMockstartRepoAPI(ctrl *gomock.Controller) *MockstartRepoAPI {
	mock := &MockstartRepoAPI{ctrl: ctrl}
	mock.recorder = &MockstartRepoAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstartRepoAPI) EXPECT() *MockstartRepoAPIMockRecorder {
	return m.recorder
}

// CancelActiveTimerObligation mocks base method.
func (m *MockstartRepoAPI) CancelActiveTimerObligation(ctx context.Context, tx *gorm.DB, sessionID uint, timer string, closedByTurnID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelActiveTimerObligation", ctx, tx, sessionID, timer, closedByTurnID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelActiveTimerObligation indicates an expected call of CancelActiveTimerObligation.
func (mr *MockstartRepoAPIMockRecorder) CancelActiveTimerObligation(ctx, tx, sessionID, timer, closedByTurnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelActiveTimerObligation", reflect.TypeOf((*MockstartRepoAPI)(nil).CancelActiveTimerObligation), ctx, tx, sessionID, timer, closedByTurnID)
}

// CancelAllActiveTimerObligationsForSession mocks base method.
func (m *MockstartRepoAPI) CancelAllActiveTimerObligationsForSession(ctx context.Context, tx *gorm.DB, sessionID uint, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelAllActiveTimerObligationsForSession", ctx, tx, sessionID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelAllActiveTimerObligationsForSession indicates an expected call of CancelAllActiveTimerObligationsForSession.
func (mr *MockstartRepoAPIMockRecorder) CancelAllActiveTimerObligationsForSession(ctx, tx, sessionID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelAllActiveTimerObligationsForSession", reflect.TypeOf((*MockstartRepoAPI)(nil).CancelAllActiveTimerObligationsForSession), ctx, tx, sessionID, reason)
}

// ClaimSessionRequest mocks base method.
func (m *MockstartRepoAPI) ClaimSessionRequest(ctx context.Context, tx *gorm.DB, input repo.ClaimSessionRequestInput) (uint, *repo.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimSessionRequest", ctx, tx, input)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(*repo.Request)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ClaimSessionRequest indicates an expected call of ClaimSessionRequest.
func (mr *MockstartRepoAPIMockRecorder) ClaimSessionRequest(ctx, tx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimSessionRequest", reflect.TypeOf((*MockstartRepoAPI)(nil).ClaimSessionRequest), ctx, tx, input)
}

// CompleteSessionRequest mocks base method.
func (m *MockstartRepoAPI) CompleteSessionRequest(ctx context.Context, tx *gorm.DB, requestID uint, sessionID *uint, outcome, responsePayload string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteSessionRequest", ctx, tx, requestID, sessionID, outcome, responsePayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteSessionRequest indicates an expected call of CompleteSessionRequest.
func (mr *MockstartRepoAPIMockRecorder) CompleteSessionRequest(ctx, tx, requestID, sessionID, outcome, responsePayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteSessionRequest", reflect.TypeOf((*MockstartRepoAPI)(nil).CompleteSessionRequest), ctx, tx, requestID, sessionID, outcome, responsePayload)
}

// CreateRuntimeFailure mocks base method.
func (m *MockstartRepoAPI) CreateRuntimeFailure(ctx context.Context, tx *gorm.DB, sessionID uint, failureKind, errorCode, errorMessage string, baseTurnID *uint, attemptedSequence uint64, sourceKind string, sourceTimerObligationID, actorID *uint, diagnosticPayload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRuntimeFailure", ctx, tx, sessionID, failureKind, errorCode, errorMessage, baseTurnID, attemptedSequence, sourceKind, sourceTimerObligationID, actorID, diagnosticPayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRuntimeFailure indicates an expected call of CreateRuntimeFailure.
func (mr *MockstartRepoAPIMockRecorder) CreateRuntimeFailure(ctx, tx, sessionID, failureKind, errorCode, errorMessage, baseTurnID, attemptedSequence, sourceKind, sourceTimerObligationID, actorID, diagnosticPayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRuntimeFailure", reflect.TypeOf((*MockstartRepoAPI)(nil).CreateRuntimeFailure), ctx, tx, sessionID, failureKind, errorCode, errorMessage, baseTurnID, attemptedSequence, sourceKind, sourceTimerObligationID, actorID, diagnosticPayload)
}

// CreateRuntimeTurn mocks base method.
func (m *MockstartRepoAPI) CreateRuntimeTurn(ctx context.Context, tx *gorm.DB, sessionID uint, sequence uint64, sourceKind string, sourceTimerObligationID, sourceCauseEventID, actorID *uint, newState json.RawMessage) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRuntimeTurn", ctx, tx, sessionID, sequence, sourceKind, sourceTimerObligationID, sourceCauseEventID, actorID, newState)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRuntimeTurn indicates an expected call of CreateRuntimeTurn.
func (mr *MockstartRepoAPIMockRecorder) CreateRuntimeTurn(ctx, tx, sessionID, sequence, sourceKind, sourceTimerObligationID, sourceCauseEventID, actorID, newState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRuntimeTurn", reflect.TypeOf((*MockstartRepoAPI)(nil).CreateRuntimeTurn), ctx, tx, sessionID, sequence, sourceKind, sourceTimerObligationID, sourceCauseEventID, actorID, newState)
}

// CreateTimerObligation mocks base method.
func (m *MockstartRepoAPI) CreateTimerObligation(ctx context.Context, tx *gorm.DB, sessionID uint, timer string, data []byte, delayMs int64, createdByTurnID uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTimerObligation", ctx, tx, sessionID, timer, data, delayMs, createdByTurnID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTimerObligation indicates an expected call of CreateTimerObligation.
func (mr *MockstartRepoAPIMockRecorder) CreateTimerObligation(ctx, tx, sessionID, timer, data, delayMs, createdByTurnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTimerObligation", reflect.TypeOf((*MockstartRepoAPI)(nil).CreateTimerObligation), ctx, tx, sessionID, timer, data, delayMs, createdByTurnID)
}

// FindActor mocks base method.
func (m *MockstartRepoAPI) FindActor(ctx context.Context, tx *gorm.DB, sessionID uint, userUUID string) (*repo.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActor", ctx, tx, sessionID, userUUID)
	ret0, _ := ret[0].(*repo.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActor indicates an expected call of FindActor.
func (mr *MockstartRepoAPIMockRecorder) FindActor(ctx, tx, sessionID, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActor", reflect.TypeOf((*MockstartRepoAPI)(nil).FindActor), ctx, tx, sessionID, userUUID)
}

// GetGameVersionArtifact mocks base method.
func (m *MockstartRepoAPI) GetGameVersionArtifact(ctx context.Context, tx *gorm.DB, definitionUUID string) (*repo.GameVersionArtifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameVersionArtifact", ctx, tx, definitionUUID)
	ret0, _ := ret[0].(*repo.GameVersionArtifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameVersionArtifact indicates an expected call of GetGameVersionArtifact.
func (mr *MockstartRepoAPIMockRecorder) GetGameVersionArtifact(ctx, tx, definitionUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameVersionArtifact", reflect.TypeOf((*MockstartRepoAPI)(nil).GetGameVersionArtifact), ctx, tx, definitionUUID)
}

// ListActiveParticipantsForRoster mocks base method.
func (m *MockstartRepoAPI) ListActiveParticipantsForRoster(ctx context.Context, tx *gorm.DB, sessionID uint) ([]repo.RosterParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveParticipantsForRoster", ctx, tx, sessionID)
	ret0, _ := ret[0].([]repo.RosterParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveParticipantsForRoster indicates an expected call of ListActiveParticipantsForRoster.
func (mr *MockstartRepoAPIMockRecorder) ListActiveParticipantsForRoster(ctx, tx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveParticipantsForRoster", reflect.TypeOf((*MockstartRepoAPI)(nil).ListActiveParticipantsForRoster), ctx, tx, sessionID)
}

// LockSessionByUUID mocks base method.
func (m *MockstartRepoAPI) LockSessionByUUID(ctx context.Context, tx *gorm.DB, sessionUUID string) (*repo.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockSessionByUUID", ctx, tx, sessionUUID)
	ret0, _ := ret[0].(*repo.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockSessionByUUID indicates an expected call of LockSessionByUUID.
func (mr *MockstartRepoAPIMockRecorder) LockSessionByUUID(ctx, tx, sessionUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockSessionByUUID", reflect.TypeOf((*MockstartRepoAPI)(nil).LockSessionByUUID), ctx, tx, sessionUUID)
}

// RevokeActiveJoinCode mocks base method.
func (m *MockstartRepoAPI) RevokeActiveJoinCode(ctx context.Context, tx *gorm.DB, sessionID uint, revokedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeActiveJoinCode", ctx, tx, sessionID, revokedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeActiveJoinCode indicates an expected call of RevokeActiveJoinCode.
func (mr *MockstartRepoAPIMockRecorder) RevokeActiveJoinCode(ctx, tx, sessionID, revokedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeActiveJoinCode", reflect.TypeOf((*MockstartRepoAPI)(nil).RevokeActiveJoinCode), ctx, tx, sessionID, revokedAt)
}

// SetCurrentTurn mocks base method.
func (m *MockstartRepoAPI) SetCurrentTurn(ctx context.Context, tx *gorm.DB, sessionID, currentTurnID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCurrentTurn", ctx, tx, sessionID, currentTurnID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCurrentTurn indicates an expected call of SetCurrentTurn.
func (mr *MockstartRepoAPIMockRecorder) SetCurrentTurn(ctx, tx, sessionID, currentTurnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCurrentTurn", reflect.TypeOf((*MockstartRepoAPI)(nil).SetCurrentTurn), ctx, tx, sessionID, currentTurnID)
}

// SetSessionRunning mocks base method.
func (m *MockstartRepoAPI) SetSessionRunning(ctx context.Context, tx *gorm.DB, sessionID uint, startedAt, activityExpiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSessionRunning", ctx, tx, sessionID, startedAt, activityExpiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSessionRunning indicates an expected call of SetSessionRunning.
func (mr *MockstartRepoAPIMockRecorder) SetSessionRunning(ctx, tx, sessionID, startedAt, activityExpiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionRunning", reflect.TypeOf((*MockstartRepoAPI)(nil).SetSessionRunning), ctx, tx, sessionID, startedAt, activityExpiresAt)
}

// SetSessionTerminal mocks base method.
func (m *MockstartRepoAPI) SetSessionTerminal(ctx context.Context, tx *gorm.DB, sessionID uint, terminalAt time.Time, terminalReason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSessionTerminal", ctx, tx, sessionID, terminalAt, terminalReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSessionTerminal indicates an expected call of SetSessionTerminal.
func (mr *MockstartRepoAPIMockRecorder) SetSessionTerminal(ctx, tx, sessionID, terminalAt, terminalReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionTerminal", reflect.TypeOf((*MockstartRepoAPI)(nil).SetSessionTerminal), ctx, tx, sessionID, terminalAt, terminalReason)
}

// MocksubmitPlayerEventRepoAPI is a mock of submitPlayerEventRepoAPI interface.
type MocksubmitPlayerEventRepoAPI struct {
	ctrl     *gomock.Controller
	recorder *MocksubmitPlayerEventRepoAPIMockRecorder
	isgomock struct{}
}

// MocksubmitPlayerEventRepoAPIMockRecorder is the mock recorder for MocksubmitPlayerEventRepoAPI.
type MocksubmitPlayerEventRepoAPIMockRecorder struct {
	mock *MocksubmitPlayerEventRepoAPI
}

// NewMocksubmitPlayerEventRepoAPI creates a new mock instance.
func NewMocksubmitPlayerEventRepoAPI(ctrl *gomock.Controller) *MocksubmitPlayerEventRepoAPI {
	mock := &MocksubmitPlayerEventRepoAPI{ctrl: ctrl}
	mock.recorder = &MocksubmitPlayerEventRepoAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksubmitPlayerEventRepoAPI) EXPECT() *MocksubmitPlayerEventRepoAPIMockRecorder {
	return m.recorder
}

// CancelActiveTimerObligation mocks base method.
func (m *MocksubmitPlayerEventRepoAPI) CancelActiveTimerObligation(ctx context.Context, tx *gorm.DB, sessionID uint, timer string, closedByTurnID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelActiveTimerObligation", ctx, tx, sessionID, timer, closedByTurnID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelActiveTimerObligation indicates an expected call of CancelActiveTimerObligation.
func (mr *MocksubmitPlayerEventRepoAPIMockRecorder) CancelActiveTimerObligation(ctx, tx, sessionID, timer, closedByTurnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelActiveTimerObligation", reflect.TypeOf((*MocksubmitPlayerEventRepoAPI)(nil).CancelActiveTimerObligation), ctx, tx, sessionID, timer, closedByTurnID)
}

// CancelAllActiveTimerObligationsForSession mocks base method.
func (m *MocksubmitPlayerEventRepoAPI) CancelAllActiveTimerObligationsForSession(ctx context.Context, tx *gorm.DB, sessionID uint, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelAllActiveTimerObligationsForSession", ctx, tx, sessionID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelAllActiveTimerObligationsForSession indicates an expected call of CancelAllActiveTimerObligationsForSession.
func (mr *MocksubmitPlayerEventRepoAPIMockRecorder) CancelAllActiveTimerObligationsForSession(ctx, tx, sessionID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelAllActiveTimerObligationsForSession", reflect.TypeOf((*MocksubmitPlayerEventRepoAPI)(nil).CancelAllActiveTimerObligationsForSession), ctx, tx, sessionID, reason)
}

// ClaimSessionRequest mocks base method.
func (m *MocksubmitPlayerEventRepoAPI) ClaimSessionRequest(ctx context.Context, tx *gorm.DB, input repo.ClaimSessionRequestInput) (uint, *repo.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimSessionRequest", ctx, tx, input)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(*repo.Request)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ClaimSessionRequest indicates an expected call of ClaimSessionRequest.
func (mr *MocksubmitPlayerEventRepoAPIMockRecorder) ClaimSessionRequest(ctx, tx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimSessionRequest", reflect.TypeOf((*MocksubmitPlayerEventRepoAPI)(nil).ClaimSessionRequest), ctx, tx, input)
}

// CompleteSessionRequest mocks base method.
func (m *MocksubmitPlayerEventRepoAPI) CompleteSessionRequest(ctx context.Context, tx *gorm.DB, requestID uint, sessionID *uint, outcome, responsePayload string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteSessionRequest", ctx, tx, requestID, sessionID, outcome, responsePayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteSessionRequest indicates an expected call of CompleteSessionRequest.
func (mr *MocksubmitPlayerEventRepoAPIMockRecorder) CompleteSessionRequest(ctx, tx, requestID, sessionID, outcome, responsePayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteSessionRequest", reflect.TypeOf((*MocksubmitPlayerEventRepoAPI)(nil).CompleteSessionRequest), ctx, tx, requestID, sessionID, outcome, responsePayload)
}

// CreateCauseEvent mocks base method.
func (m *MocksubmitPlayerEventRepoAPI) CreateCauseEvent(ctx context.Context, tx *gorm.DB, sessionID, runtimeTurnID uint, causeKind string, actorID *uint, payload []byte) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCauseEvent", ctx, tx, sessionID, runtimeTurnID, causeKind, actorID, payload)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCauseEvent indicates an expected call of CreateCauseEvent.
func (mr *MocksubmitPlayerEventRepoAPIMockRecorder) CreateCauseEvent(ctx, tx, sessionID, runtimeTurnID, causeKind, actorID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCauseEvent", reflect.TypeOf((*MocksubmitPlayerEventRepoAPI)(nil).CreateCauseEvent), ctx, tx, sessionID, runtimeTurnID, causeKind, actorID, payload)
}

// CreateRuntimeFailure mocks base method.
func (m *MocksubmitPlayerEventRepoAPI) CreateRuntimeFailure(ctx context.Context, tx *gorm.DB, sessionID uint, failureKind, errorCode, errorMessage string, baseTurnID *uint, attemptedSequence uint64, sourceKind string, sourceTimerObligationID, actorID *uint, diagnosticPayload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRuntimeFailure", ctx, tx, sessionID, failureKind, errorCode, errorMessage, baseTurnID, attemptedSequence, sourceKind, sourceTimerObligationID, actorID, diagnosticPayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRuntimeFailure indicates an expected call of CreateRuntimeFailure.
func (mr *MocksubmitPlayerEventRepoAPIMockRecorder) CreateRuntimeFailure(ctx, tx, sessionID, failureKind, errorCode, errorMessage, baseTurnID, attemptedSequence, sourceKind, sourceTimerObligationID, actorID, diagnosticPayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRuntimeFailure", reflect.TypeOf((*MocksubmitPlayerEventRepoAPI)(nil).CreateRuntimeFailure), ctx, tx, sessionID, failureKind, errorCode, errorMessage, baseTurnID, attemptedSequence, sourceKind, sourceTimerObligationID, actorID, diagnosticPayload)
}

// CreateRuntimeTurn mocks base method.
func (m *MocksubmitPlayerEventRepoAPI) CreateRuntimeTurn(ctx context.Context, tx *gorm.DB, sessionID uint, sequence uint64, sourceKind string, sourceTimerObligationID, sourceCauseEventID, actorID *uint, newState json.RawMessage) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRuntimeTurn", ctx, tx, sessionID, sequence, sourceKind, sourceTimerObligationID, sourceCauseEventID, actorID, newState)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRuntimeTurn indicates an expected call of CreateRuntimeTurn.
func (mr *MocksubmitPlayerEventRepoAPIMockRecorder) CreateRuntimeTurn(ctx, tx, sessionID, sequence, sourceKind, sourceTimerObligationID, sourceCauseEventID, actorID, newState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRuntimeTurn", reflect.TypeOf((*MocksubmitPlayerEventRepoAPI)(nil).CreateRuntimeTurn), ctx, tx, sessionID, sequence, sourceKind, sourceTimerObligationID, sourceCauseEventID, actorID, newState)
}

// CreateTimerObligation mocks base method.
func (m *MocksubmitPlayerEventRepoAPI) CreateTimerObligation(ctx context.Context, tx *gorm.DB, sessionID uint, timer string, data []byte, delayMs int64, createdByTurnID uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTimerObligation", ctx, tx, sessionID, timer, data, delayMs, createdByTurnID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTimerObligation indicates an expected call of CreateTimerObligation.
func (mr *MocksubmitPlayerEventRepoAPIMockRecorder) CreateTimerObligation(ctx, tx, sessionID, timer, data, delayMs, createdByTurnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTimerObligation", reflect.TypeOf((*MocksubmitPlayerEventRepoAPI)(nil).CreateTimerObligation), ctx, tx, sessionID, timer, data, delayMs, createdByTurnID)
}

// FindActor mocks base method.
func (m *MocksubmitPlayerEventRepoAPI) FindActor(ctx context.Context, tx *gorm.DB, sessionID uint, userUUID string) (*repo.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActor", ctx, tx, sessionID, userUUID)
	ret0, _ := ret[0].(*repo.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActor indicates an expected call of FindActor.
func (mr *MocksubmitPlayerEventRepoAPIMockRecorder) FindActor(ctx, tx, sessionID, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActor", reflect.TypeOf((*MocksubmitPlayerEventRepoAPI)(nil).FindActor), ctx, tx, sessionID, userUUID)
}

// GetGameVersionArtifact mocks base method.
func (m *MocksubmitPlayerEventRepoAPI) GetGameVersionArtifact(ctx context.Context, tx *gorm.DB, definitionUUID string) (*repo.GameVersionArtifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameVersionArtifact", ctx, tx, definitionUUID)
	ret0, _ := ret[0].(*repo.GameVersionArtifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameVersionArtifact indicates an expected call of GetGameVersionArtifact.
func (mr *MocksubmitPlayerEventRepoAPIMockRecorder) GetGameVersionArtifact(ctx, tx, definitionUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameVersionArtifact", reflect.TypeOf((*MocksubmitPlayerEventRepoAPI)(nil).GetGameVersionArtifact), ctx, tx, definitionUUID)
}

// GetRuntimeTurn mocks base method.
func (m *MocksubmitPlayerEventRepoAPI) GetRuntimeTurn(ctx context.Context, tx *gorm.DB, turnID uint) (*repo.RuntimeTurn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRuntimeTurn", ctx, tx, turnID)
	ret0, _ := ret[0].(*repo.RuntimeTurn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRuntimeTurn indicates an expected call of GetRuntimeTurn.
func (mr *MocksubmitPlayerEventRepoAPIMockRecorder) GetRuntimeTurn(ctx, tx, turnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRuntimeTurn", reflect.TypeOf((*MocksubmitPlayerEventRepoAPI)(nil).GetRuntimeTurn), ctx, tx, turnID)
}

// ListActiveParticipantsForRoster mocks base method.
func (m *MocksubmitPlayerEventRepoAPI) ListActiveParticipantsForRoster(ctx context.Context, tx *gorm.DB, sessionID uint) ([]repo.RosterParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveParticipantsForRoster", ctx, tx, sessionID)
	ret0, _ := ret[0].([]repo.RosterParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveParticipantsForRoster indicates an expected call of ListActiveParticipantsForRoster.
func (mr *MocksubmitPlayerEventRepoAPIMockRecorder) ListActiveParticipantsForRoster(ctx, tx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveParticipantsForRoster", reflect.TypeOf((*MocksubmitPlayerEventRepoAPI)(nil).ListActiveParticipantsForRoster), ctx, tx, sessionID)
}

// LockSessionByUUID mocks base method.
func (m *MocksubmitPlayerEventRepoAPI) LockSessionByUUID(ctx context.Context, tx *gorm.DB, sessionUUID string) (*repo.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockSessionByUUID", ctx, tx, sessionUUID)
	ret0, _ := ret[0].(*repo.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockSessionByUUID indicates an expected call of LockSessionByUUID.
func (mr *MocksubmitPlayerEventRepoAPIMockRecorder) LockSessionByUUID(ctx, tx, sessionUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockSessionByUUID", reflect.TypeOf((*MocksubmitPlayerEventRepoAPI)(nil).LockSessionByUUID), ctx, tx, sessionUUID)
}

// RenewActivityDeadline mocks base method.
func (m *MocksubmitPlayerEventRepoAPI) RenewActivityDeadline(ctx context.Context, tx *gorm.DB, sessionID uint, activityExpiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenewActivityDeadline", ctx, tx, sessionID, activityExpiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenewActivityDeadline indicates an expected call of RenewActivityDeadline.
func (mr *MocksubmitPlayerEventRepoAPIMockRecorder) RenewActivityDeadline(ctx, tx, sessionID, activityExpiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewActivityDeadline", reflect.TypeOf((*MocksubmitPlayerEventRepoAPI)(nil).RenewActivityDeadline), ctx, tx, sessionID, activityExpiresAt)
}

// SetCurrentTurn mocks base method.
func (m *MocksubmitPlayerEventRepoAPI) SetCurrentTurn(ctx context.Context, tx *gorm.DB, sessionID, currentTurnID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCurrentTurn", ctx, tx, sessionID, currentTurnID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCurrentTurn indicates an expected call of SetCurrentTurn.
func (mr *MocksubmitPlayerEventRepoAPIMockRecorder) SetCurrentTurn(ctx, tx, sessionID, currentTurnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCurrentTurn", reflect.TypeOf((*MocksubmitPlayerEventRepoAPI)(nil).SetCurrentTurn), ctx, tx, sessionID, currentTurnID)
}

// SetRuntimeTurnCauseEvent mocks base method.
func (m *MocksubmitPlayerEventRepoAPI) SetRuntimeTurnCauseEvent(ctx context.Context, tx *gorm.DB, turnID, causeEventID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRuntimeTurnCauseEvent", ctx, tx, turnID, causeEventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRuntimeTurnCauseEvent indicates an expected call of SetRuntimeTurnCauseEvent.
func (mr *MocksubmitPlayerEventRepoAPIMockRecorder) SetRuntimeTurnCauseEvent(ctx, tx, turnID, causeEventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRuntimeTurnCauseEvent", reflect.TypeOf((*MocksubmitPlayerEventRepoAPI)(nil).SetRuntimeTurnCauseEvent), ctx, tx, turnID, causeEventID)
}

// SetSessionTerminal mocks base method.
func (m *MocksubmitPlayerEventRepoAPI) SetSessionTerminal(ctx context.Context, tx *gorm.DB, sessionID uint, terminalAt time.Time, terminalReason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSessionTerminal", ctx, tx, sessionID, terminalAt, terminalReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSessionTerminal indicates an expected call of SetSessionTerminal.
func (mr *MocksubmitPlayerEventRepoAPIMockRecorder) SetSessionTerminal(ctx, tx, sessionID, terminalAt, terminalReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionTerminal", reflect.TypeOf((*MocksubmitPlayerEventRepoAPI)(nil).SetSessionTerminal), ctx, tx, sessionID, terminalAt, terminalReason)
}

// MockexpireTimerRepoAPI is a mock of expireTimerRepoAPI interface.
type MockexpireTimerRepoAPI struct {
	ctrl     *gomock.Controller
	recorder *MockexpireTimerRepoAPIMockRecorder
	isgomock struct{}
}

// MockexpireTimerRepoAPIMockRecorder is the mock recorder for MockexpireTimerRepoAPI.
type MockexpireTimerRepoAPIMockRecorder struct {
	mock *MockexpireTimerRepoAPI
}

// NewMockexpireTimerRepoAPI creates a new mock instance.
func NewMockexpireTimerRepoAPI(ctrl *gomock.Controller) *MockexpireTimerRepoAPI {
	mock := &MockexpireTimerRepoAPI{ctrl: ctrl}
	mock.recorder = &MockexpireTimerRepoAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockexpireTimerRepoAPI) EXPECT() *MockexpireTimerRepoAPIMockRecorder {
	return m.recorder
}

// CancelActiveTimerObligation mocks base method.
func (m *MockexpireTimerRepoAPI) CancelActiveTimerObligation(ctx context.Context, tx *gorm.DB, sessionID uint, timer string, closedByTurnID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelActiveTimerObligation", ctx, tx, sessionID, timer, closedByTurnID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelActiveTimerObligation indicates an expected call of CancelActiveTimerObligation.
func (mr *MockexpireTimerRepoAPIMockRecorder) CancelActiveTimerObligation(ctx, tx, sessionID, timer, closedByTurnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelActiveTimerObligation", reflect.TypeOf((*MockexpireTimerRepoAPI)(nil).CancelActiveTimerObligation), ctx, tx, sessionID, timer, closedByTurnID)
}

// CancelAllActiveTimerObligationsForSession mocks base method.
func (m *MockexpireTimerRepoAPI) CancelAllActiveTimerObligationsForSession(ctx context.Context, tx *gorm.DB, sessionID uint, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelAllActiveTimerObligationsForSession", ctx, tx, sessionID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelAllActiveTimerObligationsForSession indicates an expected call of CancelAllActiveTimerObligationsForSession.
func (mr *MockexpireTimerRepoAPIMockRecorder) CancelAllActiveTimerObligationsForSession(ctx, tx, sessionID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelAllActiveTimerObligationsForSession", reflect.TypeOf((*MockexpireTimerRepoAPI)(nil).CancelAllActiveTimerObligationsForSession), ctx, tx, sessionID, reason)
}

// CloseTimerObligation mocks base method.
func (m *MockexpireTimerRepoAPI) CloseTimerObligation(ctx context.Context, tx *gorm.DB, timerObligationID, closedByTurnID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseTimerObligation", ctx, tx, timerObligationID, closedByTurnID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseTimerObligation indicates an expected call of CloseTimerObligation.
func (mr *MockexpireTimerRepoAPIMockRecorder) CloseTimerObligation(ctx, tx, timerObligationID, closedByTurnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseTimerObligation", reflect.TypeOf((*MockexpireTimerRepoAPI)(nil).CloseTimerObligation), ctx, tx, timerObligationID, closedByTurnID)
}

// CreateRuntimeFailure mocks base method.
func (m *MockexpireTimerRepoAPI) CreateRuntimeFailure(ctx context.Context, tx *gorm.DB, sessionID uint, failureKind, errorCode, errorMessage string, baseTurnID *uint, attemptedSequence uint64, sourceKind string, sourceTimerObligationID, actorID *uint, diagnosticPayload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRuntimeFailure", ctx, tx, sessionID, failureKind, errorCode, errorMessage, baseTurnID, attemptedSequence, sourceKind, sourceTimerObligationID, actorID, diagnosticPayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRuntimeFailure indicates an expected call of CreateRuntimeFailure.
func (mr *MockexpireTimerRepoAPIMockRecorder) CreateRuntimeFailure(ctx, tx, sessionID, failureKind, errorCode, errorMessage, baseTurnID, attemptedSequence, sourceKind, sourceTimerObligationID, actorID, diagnosticPayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRuntimeFailure", reflect.TypeOf((*MockexpireTimerRepoAPI)(nil).CreateRuntimeFailure), ctx, tx, sessionID, failureKind, errorCode, errorMessage, baseTurnID, attemptedSequence, sourceKind, sourceTimerObligationID, actorID, diagnosticPayload)
}

// CreateRuntimeTurn mocks base method.
func (m *MockexpireTimerRepoAPI) CreateRuntimeTurn(ctx context.Context, tx *gorm.DB, sessionID uint, sequence uint64, sourceKind string, sourceTimerObligationID, sourceCauseEventID, actorID *uint, newState json.RawMessage) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRuntimeTurn", ctx, tx, sessionID, sequence, sourceKind, sourceTimerObligationID, sourceCauseEventID, actorID, newState)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRuntimeTurn indicates an expected call of CreateRuntimeTurn.
func (mr *MockexpireTimerRepoAPIMockRecorder) CreateRuntimeTurn(ctx, tx, sessionID, sequence, sourceKind, sourceTimerObligationID, sourceCauseEventID, actorID, newState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRuntimeTurn", reflect.TypeOf((*MockexpireTimerRepoAPI)(nil).CreateRuntimeTurn), ctx, tx, sessionID, sequence, sourceKind, sourceTimerObligationID, sourceCauseEventID, actorID, newState)
}

// CreateTimerObligation mocks base method.
func (m *MockexpireTimerRepoAPI) CreateTimerObligation(ctx context.Context, tx *gorm.DB, sessionID uint, timer string, data []byte, delayMs int64, createdByTurnID uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTimerObligation", ctx, tx, sessionID, timer, data, delayMs, createdByTurnID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTimerObligation indicates an expected call of CreateTimerObligation.
func (mr *MockexpireTimerRepoAPIMockRecorder) CreateTimerObligation(ctx, tx, sessionID, timer, data, delayMs, createdByTurnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTimerObligation", reflect.TypeOf((*MockexpireTimerRepoAPI)(nil).CreateTimerObligation), ctx, tx, sessionID, timer, data, delayMs, createdByTurnID)
}

// FindTimerObligationByUUID mocks base method.
func (m *MockexpireTimerRepoAPI) FindTimerObligationByUUID(ctx context.Context, tx *gorm.DB, timerObligationUUID string) (*repo.TimerObligation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTimerObligationByUUID", ctx, tx, timerObligationUUID)
	ret0, _ := ret[0].(*repo.TimerObligation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTimerObligationByUUID indicates an expected call of FindTimerObligationByUUID.
func (mr *MockexpireTimerRepoAPIMockRecorder) FindTimerObligationByUUID(ctx, tx, timerObligationUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTimerObligationByUUID", reflect.TypeOf((*MockexpireTimerRepoAPI)(nil).FindTimerObligationByUUID), ctx, tx, timerObligationUUID)
}

// GetGameVersionArtifact mocks base method.
func (m *MockexpireTimerRepoAPI) GetGameVersionArtifact(ctx context.Context, tx *gorm.DB, definitionUUID string) (*repo.GameVersionArtifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameVersionArtifact", ctx, tx, definitionUUID)
	ret0, _ := ret[0].(*repo.GameVersionArtifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameVersionArtifact indicates an expected call of GetGameVersionArtifact.
func (mr *MockexpireTimerRepoAPIMockRecorder) GetGameVersionArtifact(ctx, tx, definitionUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameVersionArtifact", reflect.TypeOf((*MockexpireTimerRepoAPI)(nil).GetGameVersionArtifact), ctx, tx, definitionUUID)
}

// GetRuntimeTurn mocks base method.
func (m *MockexpireTimerRepoAPI) GetRuntimeTurn(ctx context.Context, tx *gorm.DB, turnID uint) (*repo.RuntimeTurn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRuntimeTurn", ctx, tx, turnID)
	ret0, _ := ret[0].(*repo.RuntimeTurn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRuntimeTurn indicates an expected call of GetRuntimeTurn.
func (mr *MockexpireTimerRepoAPIMockRecorder) GetRuntimeTurn(ctx, tx, turnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRuntimeTurn", reflect.TypeOf((*MockexpireTimerRepoAPI)(nil).GetRuntimeTurn), ctx, tx, turnID)
}

// ListActiveParticipantsForRoster mocks base method.
func (m *MockexpireTimerRepoAPI) ListActiveParticipantsForRoster(ctx context.Context, tx *gorm.DB, sessionID uint) ([]repo.RosterParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveParticipantsForRoster", ctx, tx, sessionID)
	ret0, _ := ret[0].([]repo.RosterParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveParticipantsForRoster indicates an expected call of ListActiveParticipantsForRoster.
func (mr *MockexpireTimerRepoAPIMockRecorder) ListActiveParticipantsForRoster(ctx, tx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveParticipantsForRoster", reflect.TypeOf((*MockexpireTimerRepoAPI)(nil).ListActiveParticipantsForRoster), ctx, tx, sessionID)
}

// LockSessionByID mocks base method.
func (m *MockexpireTimerRepoAPI) LockSessionByID(ctx context.Context, tx *gorm.DB, sessionID uint) (*repo.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockSessionByID", ctx, tx, sessionID)
	ret0, _ := ret[0].(*repo.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockSessionByID indicates an expected call of LockSessionByID.
func (mr *MockexpireTimerRepoAPIMockRecorder) LockSessionByID(ctx, tx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockSessionByID", reflect.TypeOf((*MockexpireTimerRepoAPI)(nil).LockSessionByID), ctx, tx, sessionID)
}

// RenewActivityDeadline mocks base method.
func (m *MockexpireTimerRepoAPI) RenewActivityDeadline(ctx context.Context, tx *gorm.DB, sessionID uint, activityExpiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenewActivityDeadline", ctx, tx, sessionID, activityExpiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenewActivityDeadline indicates an expected call of RenewActivityDeadline.
func (mr *MockexpireTimerRepoAPIMockRecorder) RenewActivityDeadline(ctx, tx, sessionID, activityExpiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewActivityDeadline", reflect.TypeOf((*MockexpireTimerRepoAPI)(nil).RenewActivityDeadline), ctx, tx, sessionID, activityExpiresAt)
}

// ResolveSessionForTimerObligation mocks base method.
func (m *MockexpireTimerRepoAPI) ResolveSessionForTimerObligation(ctx context.Context, timerObligationUUID string) (*uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveSessionForTimerObligation", ctx, timerObligationUUID)
	ret0, _ := ret[0].(*uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveSessionForTimerObligation indicates an expected call of ResolveSessionForTimerObligation.
func (mr *MockexpireTimerRepoAPIMockRecorder) ResolveSessionForTimerObligation(ctx, timerObligationUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveSessionForTimerObligation", reflect.TypeOf((*MockexpireTimerRepoAPI)(nil).ResolveSessionForTimerObligation), ctx, timerObligationUUID)
}

// SetCurrentTurn mocks base method.
func (m *MockexpireTimerRepoAPI) SetCurrentTurn(ctx context.Context, tx *gorm.DB, sessionID, currentTurnID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCurrentTurn", ctx, tx, sessionID, currentTurnID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCurrentTurn indicates an expected call of SetCurrentTurn.
func (mr *MockexpireTimerRepoAPIMockRecorder) SetCurrentTurn(ctx, tx, sessionID, currentTurnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCurrentTurn", reflect.TypeOf((*MockexpireTimerRepoAPI)(nil).SetCurrentTurn), ctx, tx, sessionID, currentTurnID)
}

// SetSessionTerminal mocks base method.
func (m *MockexpireTimerRepoAPI) SetSessionTerminal(ctx context.Context, tx *gorm.DB, sessionID uint, terminalAt time.Time, terminalReason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSessionTerminal", ctx, tx, sessionID, terminalAt, terminalReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSessionTerminal indicates an expected call of SetSessionTerminal.
func (mr *MockexpireTimerRepoAPIMockRecorder) SetSessionTerminal(ctx, tx, sessionID, terminalAt, terminalReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionTerminal", reflect.TypeOf((*MockexpireTimerRepoAPI)(nil).SetSessionTerminal), ctx, tx, sessionID, terminalAt, terminalReason)
}

// MockcancelSessionRepoAPI is a mock of cancelSessionRepoAPI interface.
type MockcancelSessionRepoAPI struct {
	ctrl     *gomock.Controller
	recorder *MockcancelSessionRepoAPIMockRecorder
	isgomock struct{}
}

// MockcancelSessionRepoAPIMockRecorder is the mock recorder for MockcancelSessionRepoAPI.
type MockcancelSessionRepoAPIMockRecorder struct {
	mock *MockcancelSessionRepoAPI
}

// NewMockcancelSessionRepoAPI creates a new mock instance.
func NewMockcancelSessionRepoAPI(ctrl *gomock.Controller) *MockcancelSessionRepoAPI {
	mock := &MockcancelSessionRepoAPI{ctrl: ctrl}
	mock.recorder = &MockcancelSessionRepoAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcancelSessionRepoAPI) EXPECT() *MockcancelSessionRepoAPIMockRecorder {
	return m.recorder
}

// CancelActiveTimerObligation mocks base method.
func (m *MockcancelSessionRepoAPI) CancelActiveTimerObligation(ctx context.Context, tx *gorm.DB, sessionID uint, timer string, closedByTurnID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelActiveTimerObligation", ctx, tx, sessionID, timer, closedByTurnID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelActiveTimerObligation indicates an expected call of CancelActiveTimerObligation.
func (mr *MockcancelSessionRepoAPIMockRecorder) CancelActiveTimerObligation(ctx, tx, sessionID, timer, closedByTurnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelActiveTimerObligation", reflect.TypeOf((*MockcancelSessionRepoAPI)(nil).CancelActiveTimerObligation), ctx, tx, sessionID, timer, closedByTurnID)
}

// CancelAllActiveTimerObligationsForSession mocks base method.
func (m *MockcancelSessionRepoAPI) CancelAllActiveTimerObligationsForSession(ctx context.Context, tx *gorm.DB, sessionID uint, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelAllActiveTimerObligationsForSession", ctx, tx, sessionID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelAllActiveTimerObligationsForSession indicates an expected call of CancelAllActiveTimerObligationsForSession.
func (mr *MockcancelSessionRepoAPIMockRecorder) CancelAllActiveTimerObligationsForSession(ctx, tx, sessionID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelAllActiveTimerObligationsForSession", reflect.TypeOf((*MockcancelSessionRepoAPI)(nil).CancelAllActiveTimerObligationsForSession), ctx, tx, sessionID, reason)
}

// ClaimSessionRequest mocks base method.
func (m *MockcancelSessionRepoAPI) ClaimSessionRequest(ctx context.Context, tx *gorm.DB, input repo.ClaimSessionRequestInput) (uint, *repo.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimSessionRequest", ctx, tx, input)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(*repo.Request)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ClaimSessionRequest indicates an expected call of ClaimSessionRequest.
func (mr *MockcancelSessionRepoAPIMockRecorder) ClaimSessionRequest(ctx, tx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimSessionRequest", reflect.TypeOf((*MockcancelSessionRepoAPI)(nil).ClaimSessionRequest), ctx, tx, input)
}

// CompleteSessionRequest mocks base method.
func (m *MockcancelSessionRepoAPI) CompleteSessionRequest(ctx context.Context, tx *gorm.DB, requestID uint, sessionID *uint, outcome, responsePayload string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteSessionRequest", ctx, tx, requestID, sessionID, outcome, responsePayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteSessionRequest indicates an expected call of CompleteSessionRequest.
func (mr *MockcancelSessionRepoAPIMockRecorder) CompleteSessionRequest(ctx, tx, requestID, sessionID, outcome, responsePayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteSessionRequest", reflect.TypeOf((*MockcancelSessionRepoAPI)(nil).CompleteSessionRequest), ctx, tx, requestID, sessionID, outcome, responsePayload)
}

// CreateCauseEvent mocks base method.
func (m *MockcancelSessionRepoAPI) CreateCauseEvent(ctx context.Context, tx *gorm.DB, sessionID, runtimeTurnID uint, causeKind string, actorID *uint, payload []byte) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCauseEvent", ctx, tx, sessionID, runtimeTurnID, causeKind, actorID, payload)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCauseEvent indicates an expected call of CreateCauseEvent.
func (mr *MockcancelSessionRepoAPIMockRecorder) CreateCauseEvent(ctx, tx, sessionID, runtimeTurnID, causeKind, actorID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCauseEvent", reflect.TypeOf((*MockcancelSessionRepoAPI)(nil).CreateCauseEvent), ctx, tx, sessionID, runtimeTurnID, causeKind, actorID, payload)
}

// CreateRuntimeFailure mocks base method.
func (m *MockcancelSessionRepoAPI) CreateRuntimeFailure(ctx context.Context, tx *gorm.DB, sessionID uint, failureKind, errorCode, errorMessage string, baseTurnID *uint, attemptedSequence uint64, sourceKind string, sourceTimerObligationID, actorID *uint, diagnosticPayload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRuntimeFailure", ctx, tx, sessionID, failureKind, errorCode, errorMessage, baseTurnID, attemptedSequence, sourceKind, sourceTimerObligationID, actorID, diagnosticPayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRuntimeFailure indicates an expected call of CreateRuntimeFailure.
func (mr *MockcancelSessionRepoAPIMockRecorder) CreateRuntimeFailure(ctx, tx, sessionID, failureKind, errorCode, errorMessage, baseTurnID, attemptedSequence, sourceKind, sourceTimerObligationID, actorID, diagnosticPayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRuntimeFailure", reflect.TypeOf((*MockcancelSessionRepoAPI)(nil).CreateRuntimeFailure), ctx, tx, sessionID, failureKind, errorCode, errorMessage, baseTurnID, attemptedSequence, sourceKind, sourceTimerObligationID, actorID, diagnosticPayload)
}

// CreateRuntimeTurn mocks base method.
func (m *MockcancelSessionRepoAPI) CreateRuntimeTurn(ctx context.Context, tx *gorm.DB, sessionID uint, sequence uint64, sourceKind string, sourceTimerObligationID, sourceCauseEventID, actorID *uint, newState json.RawMessage) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRuntimeTurn", ctx, tx, sessionID, sequence, sourceKind, sourceTimerObligationID, sourceCauseEventID, actorID, newState)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRuntimeTurn indicates an expected call of CreateRuntimeTurn.
func (mr *MockcancelSessionRepoAPIMockRecorder) CreateRuntimeTurn(ctx, tx, sessionID, sequence, sourceKind, sourceTimerObligationID, sourceCauseEventID, actorID, newState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRuntimeTurn", reflect.TypeOf((*MockcancelSessionRepoAPI)(nil).CreateRuntimeTurn), ctx, tx, sessionID, sequence, sourceKind, sourceTimerObligationID, sourceCauseEventID, actorID, newState)
}

// CreateTimerObligation mocks base method.
func (m *MockcancelSessionRepoAPI) CreateTimerObligation(ctx context.Context, tx *gorm.DB, sessionID uint, timer string, data []byte, delayMs int64, createdByTurnID uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTimerObligation", ctx, tx, sessionID, timer, data, delayMs, createdByTurnID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTimerObligation indicates an expected call of CreateTimerObligation.
func (mr *MockcancelSessionRepoAPIMockRecorder) CreateTimerObligation(ctx, tx, sessionID, timer, data, delayMs, createdByTurnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTimerObligation", reflect.TypeOf((*MockcancelSessionRepoAPI)(nil).CreateTimerObligation), ctx, tx, sessionID, timer, data, delayMs, createdByTurnID)
}

// FindActor mocks base method.
func (m *MockcancelSessionRepoAPI) FindActor(ctx context.Context, tx *gorm.DB, sessionID uint, userUUID string) (*repo.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActor", ctx, tx, sessionID, userUUID)
	ret0, _ := ret[0].(*repo.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActor indicates an expected call of FindActor.
func (mr *MockcancelSessionRepoAPIMockRecorder) FindActor(ctx, tx, sessionID, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActor", reflect.TypeOf((*MockcancelSessionRepoAPI)(nil).FindActor), ctx, tx, sessionID, userUUID)
}

// GetGameVersionArtifact mocks base method.
func (m *MockcancelSessionRepoAPI) GetGameVersionArtifact(ctx context.Context, tx *gorm.DB, definitionUUID string) (*repo.GameVersionArtifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameVersionArtifact", ctx, tx, definitionUUID)
	ret0, _ := ret[0].(*repo.GameVersionArtifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameVersionArtifact indicates an expected call of GetGameVersionArtifact.
func (mr *MockcancelSessionRepoAPIMockRecorder) GetGameVersionArtifact(ctx, tx, definitionUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameVersionArtifact", reflect.TypeOf((*MockcancelSessionRepoAPI)(nil).GetGameVersionArtifact), ctx, tx, definitionUUID)
}

// GetRuntimeTurn mocks base method.
func (m *MockcancelSessionRepoAPI) GetRuntimeTurn(ctx context.Context, tx *gorm.DB, turnID uint) (*repo.RuntimeTurn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRuntimeTurn", ctx, tx, turnID)
	ret0, _ := ret[0].(*repo.RuntimeTurn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRuntimeTurn indicates an expected call of GetRuntimeTurn.
func (mr *MockcancelSessionRepoAPIMockRecorder) GetRuntimeTurn(ctx, tx, turnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRuntimeTurn", reflect.TypeOf((*MockcancelSessionRepoAPI)(nil).GetRuntimeTurn), ctx, tx, turnID)
}

// ListActiveParticipantsForRoster mocks base method.
func (m *MockcancelSessionRepoAPI) ListActiveParticipantsForRoster(ctx context.Context, tx *gorm.DB, sessionID uint) ([]repo.RosterParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveParticipantsForRoster", ctx, tx, sessionID)
	ret0, _ := ret[0].([]repo.RosterParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveParticipantsForRoster indicates an expected call of ListActiveParticipantsForRoster.
func (mr *MockcancelSessionRepoAPIMockRecorder) ListActiveParticipantsForRoster(ctx, tx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveParticipantsForRoster", reflect.TypeOf((*MockcancelSessionRepoAPI)(nil).ListActiveParticipantsForRoster), ctx, tx, sessionID)
}

// LockSessionByUUID mocks base method.
func (m *MockcancelSessionRepoAPI) LockSessionByUUID(ctx context.Context, tx *gorm.DB, sessionUUID string) (*repo.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockSessionByUUID", ctx, tx, sessionUUID)
	ret0, _ := ret[0].(*repo.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockSessionByUUID indicates an expected call of LockSessionByUUID.
func (mr *MockcancelSessionRepoAPIMockRecorder) LockSessionByUUID(ctx, tx, sessionUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockSessionByUUID", reflect.TypeOf((*MockcancelSessionRepoAPI)(nil).LockSessionByUUID), ctx, tx, sessionUUID)
}

// SetCurrentTurn mocks base method.
func (m *MockcancelSessionRepoAPI) SetCurrentTurn(ctx context.Context, tx *gorm.DB, sessionID, currentTurnID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCurrentTurn", ctx, tx, sessionID, currentTurnID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCurrentTurn indicates an expected call of SetCurrentTurn.
func (mr *MockcancelSessionRepoAPIMockRecorder) SetCurrentTurn(ctx, tx, sessionID, currentTurnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCurrentTurn", reflect.TypeOf((*MockcancelSessionRepoAPI)(nil).SetCurrentTurn), ctx, tx, sessionID, currentTurnID)
}

// SetRuntimeTurnCauseEvent mocks base method.
func (m *MockcancelSessionRepoAPI) SetRuntimeTurnCauseEvent(ctx context.Context, tx *gorm.DB, turnID, causeEventID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRuntimeTurnCauseEvent", ctx, tx, turnID, causeEventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRuntimeTurnCauseEvent indicates an expected call of SetRuntimeTurnCauseEvent.
func (mr *MockcancelSessionRepoAPIMockRecorder) SetRuntimeTurnCauseEvent(ctx, tx, turnID, causeEventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRuntimeTurnCauseEvent", reflect.TypeOf((*MockcancelSessionRepoAPI)(nil).SetRuntimeTurnCauseEvent), ctx, tx, turnID, causeEventID)
}

// SetSessionTerminal mocks base method.
func (m *MockcancelSessionRepoAPI) SetSessionTerminal(ctx context.Context, tx *gorm.DB, sessionID uint, terminalAt time.Time, terminalReason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSessionTerminal", ctx, tx, sessionID, terminalAt, terminalReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSessionTerminal indicates an expected call of SetSessionTerminal.
func (mr *MockcancelSessionRepoAPIMockRecorder) SetSessionTerminal(ctx, tx, sessionID, terminalAt, terminalReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionTerminal", reflect.TypeOf((*MockcancelSessionRepoAPI)(nil).SetSessionTerminal), ctx, tx, sessionID, terminalAt, terminalReason)
}
