// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/diegobermudez03/playhoot/game/session/usecases/createsession (interfaces: repoAPI,gameDefinitionResolver)
//
// Generated by this command:
//
//	mockgen -package=createsession -destination=repo_mock_test.go . repoAPI,gameDefinitionResolver
//

// Package createsession is a generated GoMock package.
package createsession

import (
	context "context"
	reflect "reflect"

	game "github.com/diegobermudez03/playhoot/game/game"
	gomock "go.uber.org/mock/gomock"
)

// MockrepoAPI is a mock of repoAPI interface.
type MockrepoAPI struct {
	ctrl     *gomock.Controller
	recorder *MockrepoAPIMockRecorder
	isgomock struct{}
}

// MockrepoAPIMockRecorder is the mock recorder for MockrepoAPI.
type MockrepoAPIMockRecorder struct {
	mock *MockrepoAPI
}

// NewMockrepoAPI creates a new mock instance.
func NewMockrepoAPI(ctrl *gomock.Controller) *MockrepoAPI {
	mock := &MockrepoAPI{ctrl: ctrl}
	mock.recorder = &MockrepoAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrepoAPI) EXPECT() *MockrepoAPIMockRecorder {
	return m.recorder
}

// createSession mocks base method.
func (m *MockrepoAPI) createSession(ctx context.Context, params createParams) (Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "createSession", ctx, params)
	ret0, _ := ret[0].(Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// createSession indicates an expected call of createSession.
func (mr *MockrepoAPIMockRecorder) createSession(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "createSession", reflect.TypeOf((*MockrepoAPI)(nil).createSession), ctx, params)
}

// MockgameDefinitionResolver is a mock of gameDefinitionResolver interface.
type MockgameDefinitionResolver struct {
	ctrl     *gomock.Controller
	recorder *MockgameDefinitionResolverMockRecorder
	isgomock struct{}
}

// MockgameDefinitionResolverMockRecorder is the mock recorder for MockgameDefinitionResolver.
type MockgameDefinitionResolverMockRecorder struct {
	mock *MockgameDefinitionResolver
}

// NewMockgameDefinitionResolver creates a new mock instance.
func NewMockgameDefinitionResolver(ctrl *gomock.Controller) *MockgameDefinitionResolver {
	mock := &MockgameDefinitionResolver{ctrl: ctrl}
	mock.recorder = &MockgameDefinitionResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgameDefinitionResolver) EXPECT() *MockgameDefinitionResolverMockRecorder {
	return m.recorder
}

// GetPlayableGameWithCurrentVersion mocks base method.
func (m *MockgameDefinitionResolver) GetPlayableGameWithCurrentVersion(ctx context.Context, gameUUID string) (*game.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayableGameWithCurrentVersion", ctx, gameUUID)
	ret0, _ := ret[0].(*game.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayableGameWithCurrentVersion indicates an expected call of GetPlayableGameWithCurrentVersion.
func (mr *MockgameDefinitionResolverMockRecorder) GetPlayableGameWithCurrentVersion(ctx, gameUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayableGameWithCurrentVersion", reflect.TypeOf((*MockgameDefinitionResolver)(nil).GetPlayableGameWithCurrentVersion), ctx, gameUUID)
}
