// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/diegobermudez03/playhoot/game/game/usecases/creategame (interfaces: repoAPI)

package creategame

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

type MockRepoAPI struct {
	ctrl     *gomock.Controller
	recorder *MockRepoAPIMockRecorder
}

type MockRepoAPIMockRecorder struct {
	mock *MockRepoAPI
}

func NewMockRepoAPI(ctrl *gomock.Controller) *MockRepoAPI {
	mock := &MockRepoAPI{ctrl: ctrl}
	mock.recorder = &MockRepoAPIMockRecorder{mock}
	return mock
}

func (m *MockRepoAPI) EXPECT() *MockRepoAPIMockRecorder {
	return m.recorder
}

func (m *MockRepoAPI) createGameDraft(ctx context.Context, params createGameDraftParams) (*createdGameDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "createGameDraft", ctx, params)
	ret0, _ := ret[0].(*createdGameDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepoAPIMockRecorder) createGameDraft(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "createGameDraft", reflect.TypeOf((*MockRepoAPI)(nil).createGameDraft), ctx, params)
}
