// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/diegobermudez03/playhoot/orchestrator (interfaces: visibilityChecker,sessionCreator)
//
// Generated by this command:
//
//	mockgen -package=orchestrator -destination=mocks_test.go . visibilityChecker,sessionCreator
//

// Package orchestrator is a generated GoMock package.
package orchestrator

import (
	context "context"
	reflect "reflect"

	session "github.com/diegobermudez03/playhoot/session"
	gomock "go.uber.org/mock/gomock"
)

// MockvisibilityChecker is a mock of visibilityChecker interface.
type MockvisibilityChecker struct {
	ctrl     *gomock.Controller
	recorder *MockvisibilityCheckerMockRecorder
	isgomock struct{}
}

// MockvisibilityCheckerMockRecorder is the mock recorder for MockvisibilityChecker.
type MockvisibilityCheckerMockRecorder struct {
	mock *MockvisibilityChecker
}

// NewMockvisibilityChecker creates a new mock instance.
func NewMockvisibilityChecker(ctrl *gomock.Controller) *MockvisibilityChecker {
	mock := &MockvisibilityChecker{ctrl: ctrl}
	mock.recorder = &MockvisibilityCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvisibilityChecker) EXPECT() *MockvisibilityCheckerMockRecorder {
	return m.recorder
}

// IsVisible mocks base method.
func (m *MockvisibilityChecker) IsVisible(ctx context.Context, gameUUID string) (bool, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsVisible", ctx, gameUUID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IsVisible indicates an expected call of IsVisible.
func (mr *MockvisibilityCheckerMockRecorder) IsVisible(ctx, gameUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsVisible", reflect.TypeOf((*MockvisibilityChecker)(nil).IsVisible), ctx, gameUUID)
}

// MocksessionCreator is a mock of sessionCreator interface.
type MocksessionCreator struct {
	ctrl     *gomock.Controller
	recorder *MocksessionCreatorMockRecorder
	isgomock struct{}
}

// MocksessionCreatorMockRecorder is the mock recorder for MocksessionCreator.
type MocksessionCreatorMockRecorder struct {
	mock *MocksessionCreator
}

// NewMocksessionCreator creates a new mock instance.
func NewMocksessionCreator(ctrl *gomock.Controller) *MocksessionCreator {
	mock := &MocksessionCreator{ctrl: ctrl}
	mock.recorder = &MocksessionCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionCreator) EXPECT() *MocksessionCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocksessionCreator) Create(ctx context.Context, gameUUID session.GameUUID, hostUserUUID session.UserUUID, idempotencyKey session.IdempotencyKey) (session.CreatedSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, gameUUID, hostUserUUID, idempotencyKey)
	ret0, _ := ret[0].(session.CreatedSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MocksessionCreatorMockRecorder) Create(ctx, gameUUID, hostUserUUID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocksessionCreator)(nil).Create), ctx, gameUUID, hostUserUUID, idempotencyKey)
}
