// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/diegobermudez03/playhoot/game/game/usecases/getgame (interfaces: repoAPI)

package getgame

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

type MockRepoAPI struct {
	ctrl     *gomock.Controller
	recorder *MockRepoAPIMockRecorder
}

type MockRepoAPIMockRecorder struct {
	mock *MockRepoAPI
}

func NewMockRepoAPI(ctrl *gomock.Controller) *MockRepoAPI {
	mock := &MockRepoAPI{ctrl: ctrl}
	mock.recorder = &MockRepoAPIMockRecorder{mock}
	return mock
}

func (m *MockRepoAPI) EXPECT() *MockRepoAPIMockRecorder {
	return m.recorder
}

func (m *MockRepoAPI) getGameCurrentVersion(ctx context.Context, gameUUID string) (*gameWithVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getGameCurrentVersion", ctx, gameUUID)
	ret0, _ := ret[0].(*gameWithVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepoAPIMockRecorder) getGameCurrentVersion(ctx, gameUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getGameCurrentVersion", reflect.TypeOf((*MockRepoAPI)(nil).getGameCurrentVersion), ctx, gameUUID)
}
