// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.0
// source: executor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Authored JavaScript source, sent inline.
	Script []byte `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	// Opaque JSON the script's own execute() function receives unexamined.
	PreviousState []byte            `protobuf:"bytes,2,opt,name=previous_state,json=previousState,proto3" json:"previous_state,omitempty"`
	Event         []byte            `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	Context       *ExecutionContext `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetScript() []byte {
	if x != nil {
		return x.Script
	}
	return nil
}

func (x *ExecuteRequest) GetPreviousState() []byte {
	if x != nil {
		return x.PreviousState
	}
	return nil
}

func (x *ExecuteRequest) GetEvent() []byte {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecuteRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type ExecutionContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFC3339Nano timestamp; the only source of "current time" the script may
	// observe, real or otherwise.
	LogicalTime string `protobuf:"bytes,1,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	// Decimal-string encoded random seed (may exceed a 64-bit integer's safe
	// range in some client languages, hence string rather than a fixed-width
	// integer type).
	RandomSeed    string `protobuf:"bytes,2,opt,name=random_seed,json=randomSeed,proto3" json:"random_seed,omitempty"`
	ActingActor   string `protobuf:"bytes,3,opt,name=acting_actor,json=actingActor,proto3" json:"acting_actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionContext) Reset() {
	*x = ExecutionContext{}
	mi := &file_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionContext) ProtoMessage() {}

func (x *ExecutionContext) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionContext.ProtoReflect.Descriptor instead.
func (*ExecutionContext) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionContext) GetLogicalTime() string {
	if x != nil {
		return x.LogicalTime
	}
	return ""
}

func (x *ExecutionContext) GetRandomSeed() string {
	if x != nil {
		return x.RandomSeed
	}
	return ""
}

func (x *ExecutionContext) GetActingActor() string {
	if x != nil {
		return x.ActingActor
	}
	return ""
}

type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*ExecuteResponse_Success
	//	*ExecuteResponse_Rejected
	Outcome       isExecuteResponse_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteResponse) GetOutcome() isExecuteResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *ExecuteResponse) GetSuccess() *Success {
	if x != nil {
		if x, ok := x.Outcome.(*ExecuteResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *ExecuteResponse) GetRejected() *Rejected {
	if x != nil {
		if x, ok := x.Outcome.(*ExecuteResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

type isExecuteResponse_Outcome interface {
	isExecuteResponse_Outcome()
}

type ExecuteResponse_Success struct {
	Success *Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type ExecuteResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,2,opt,name=rejected,proto3,oneof"`
}

func (*ExecuteResponse_Success) isExecuteResponse_Outcome() {}

func (*ExecuteResponse_Rejected) isExecuteResponse_Outcome() {}

type Success struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NewState          []byte                 `protobuf:"bytes,1,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	RequestedCommands [][]byte               `protobuf:"bytes,2,rep,name=requested_commands,json=requestedCommands,proto3" json:"requested_commands,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Success) Reset() {
	*x = Success{}
	mi := &file_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Success) ProtoMessage() {}

func (x *Success) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Success.ProtoReflect.Descriptor instead.
func (*Success) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{3}
}

func (x *Success) GetNewState() []byte {
	if x != nil {
		return x.NewState
	}
	return nil
}

func (x *Success) GetRequestedCommands() [][]byte {
	if x != nil {
		return x.RequestedCommands
	}
	return nil
}

// Rejected means the script itself declined the input: it threw, returned a
// value that does not match the required shape, or defined no execute
// function. It is a business-level outcome, distinct from an RPC error,
// which indicates the Executor itself failed to run the script at all.
type Rejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rejected) Reset() {
	*x = Rejected{}
	mi := &file_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rejected) ProtoMessage() {}

func (x *Rejected) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rejected.ProtoReflect.Descriptor instead.
func (*Rejected) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{4}
}

func (x *Rejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_executor_proto protoreflect.FileDescriptor

const file_executor_proto_rawDesc = "" +
	"\n" +
	"\x0eexecutor.proto\x12\n" +
	"jsexecutor\"\x9d\x01\n" +
	"\x0eExecuteRequest\x12\x16\n" +
	"\x06script\x18\x01 \x01(\fR\x06script\x12%\n" +
	"\x0eprevious_state\x18\x02 \x01(\fR\rpreviousState\x12\x14\n" +
	"\x05event\x18\x03 \x01(\fR\x05event\x126\n" +
	"\acontext\x18\x04 \x01(\v2\x1c.jsexecutor.ExecutionContextR\acontext\"y\n" +
	"\x10ExecutionContext\x12!\n" +
	"\flogical_time\x18\x01 \x01(\tR\vlogicalTime\x12\x1f\n" +
	"\vrandom_seed\x18\x02 \x01(\tR\n" +
	"randomSeed\x12!\n" +
	"\facting_actor\x18\x03 \x01(\tR\vactingActor\"\x81\x01\n" +
	"\x0fExecuteResponse\x12/\n" +
	"\asuccess\x18\x01 \x01(\v2\x13.jsexecutor.SuccessH\x00R\asuccess\x122\n" +
	"\brejected\x18\x02 \x01(\v2\x14.jsexecutor.RejectedH\x00R\brejectedB\t\n" +
	"\aoutcome\"U\n" +
	"\aSuccess\x12\x1b\n" +
	"\tnew_state\x18\x01 \x01(\fR\bnewState\x12-\n" +
	"\x12requested_commands\x18\x02 \x03(\fR\x11requestedCommands\"\"\n" +
	"\bRejected\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason2N\n" +
	"\bExecutor\x12B\n" +
	"\aExecute\x12\x1a.jsexecutor.ExecuteRequest\x1a\x1b.jsexecutor.ExecuteResponseBCZAgithub.com/diegobermudez03/playhoot/game/session/jsexecutor/protob\x06proto3"

var (
	file_executor_proto_rawDescOnce sync.Once
	file_executor_proto_rawDescData []byte
)

func file_executor_proto_rawDescGZIP() []byte {
	file_executor_proto_rawDescOnce.Do(func() {
		file_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_executor_proto_rawDesc), len(file_executor_proto_rawDesc)))
	})
	return file_executor_proto_rawDescData
}

var file_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_executor_proto_goTypes = []any{
	(*ExecuteRequest)(nil),   // 0: jsexecutor.ExecuteRequest
	(*ExecutionContext)(nil), // 1: jsexecutor.ExecutionContext
	(*ExecuteResponse)(nil),  // 2: jsexecutor.ExecuteResponse
	(*Success)(nil),          // 3: jsexecutor.Success
	(*Rejected)(nil),         // 4: jsexecutor.Rejected
}
var file_executor_proto_depIdxs = []int32{
	1, // 0: jsexecutor.ExecuteRequest.context:type_name -> jsexecutor.ExecutionContext
	3, // 1: jsexecutor.ExecuteResponse.success:type_name -> jsexecutor.Success
	4, // 2: jsexecutor.ExecuteResponse.rejected:type_name -> jsexecutor.Rejected
	0, // 3: jsexecutor.Executor.Execute:input_type -> jsexecutor.ExecuteRequest
	2, // 4: jsexecutor.Executor.Execute:output_type -> jsexecutor.ExecuteResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_executor_proto_init() }
func file_executor_proto_init() {
	if File_executor_proto != nil {
		return
	}
	file_executor_proto_msgTypes[2].OneofWrappers = []any{
		(*ExecuteResponse_Success)(nil),
		(*ExecuteResponse_Rejected)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_executor_proto_rawDesc), len(file_executor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_executor_proto_goTypes,
		DependencyIndexes: file_executor_proto_depIdxs,
		MessageInfos:      file_executor_proto_msgTypes,
	}.Build()
	File_executor_proto = out.File
	file_executor_proto_goTypes = nil
	file_executor_proto_depIdxs = nil
}
