// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/diegobermudez03/playhoot/play (interfaces: SessionRuntime)
//
// Generated by this command:
//
//	mockgen -package=play -destination=sessionruntime_mock_test.go . SessionRuntime
//

// Package play is a generated GoMock package.
package play

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionRuntime is a mock of SessionRuntime interface.
type MockSessionRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRuntimeMockRecorder
	isgomock struct{}
}

// MockSessionRuntimeMockRecorder is the mock recorder for MockSessionRuntime.
type MockSessionRuntimeMockRecorder struct {
	mock *MockSessionRuntime
}

// NewMockSessionRuntime creates a new mock instance.
func NewMockSessionRuntime(ctrl *gomock.Controller) *MockSessionRuntime {
	mock := &MockSessionRuntime{ctrl: ctrl}
	mock.recorder = &MockSessionRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRuntime) EXPECT() *MockSessionRuntimeMockRecorder {
	return m.recorder
}

// AnswerInteraction mocks base method.
func (m *MockSessionRuntime) AnswerInteraction(ctx context.Context, interactionUUID, userUUID string, answer []byte) (AnswerInteractionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerInteraction", ctx, interactionUUID, userUUID, answer)
	ret0, _ := ret[0].(AnswerInteractionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnswerInteraction indicates an expected call of AnswerInteraction.
func (mr *MockSessionRuntimeMockRecorder) AnswerInteraction(ctx, interactionUUID, userUUID, answer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerInteraction", reflect.TypeOf((*MockSessionRuntime)(nil).AnswerInteraction), ctx, interactionUUID, userUUID, answer)
}

// Create mocks base method.
func (m *MockSessionRuntime) Create(ctx context.Context, gameUUID, hostUserUUID, idempotencyKey string) (CreatedSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, gameUUID, hostUserUUID, idempotencyKey)
	ret0, _ := ret[0].(CreatedSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionRuntimeMockRecorder) Create(ctx, gameUUID, hostUserUUID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRuntime)(nil).Create), ctx, gameUUID, hostUserUUID, idempotencyKey)
}

// Join mocks base method.
func (m *MockSessionRuntime) Join(ctx context.Context, joinCode uint, userUUID, displayName, idempotencyKey string) (JoinResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Join", ctx, joinCode, userUUID, displayName, idempotencyKey)
	ret0, _ := ret[0].(JoinResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Join indicates an expected call of Join.
func (mr *MockSessionRuntimeMockRecorder) Join(ctx, joinCode, userUUID, displayName, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockSessionRuntime)(nil).Join), ctx, joinCode, userUUID, displayName, idempotencyKey)
}

// Start mocks base method.
func (m *MockSessionRuntime) Start(ctx context.Context, sessionUUID, userUUID, idempotencyKey string) (StartResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, sessionUUID, userUUID, idempotencyKey)
	ret0, _ := ret[0].(StartResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockSessionRuntimeMockRecorder) Start(ctx, sessionUUID, userUUID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSessionRuntime)(nil).Start), ctx, sessionUUID, userUUID, idempotencyKey)
}
