// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/diegobermudez03/playhoot/game/session/usecases/joinsession (interfaces: repoAPI,gameDefinitionResolver)
//
// Generated by this command:
//
//	mockgen -package=joinsession -destination=repo_mock_test.go . repoAPI,gameDefinitionResolver
//

// Package joinsession is a generated GoMock package.
package joinsession

import (
	context "context"
	reflect "reflect"

	program "github.com/diegobermudez03/playhoot/game/language/v1/program"
	gomock "go.uber.org/mock/gomock"
)

// MockrepoAPI is a mock of repoAPI interface.
type MockrepoAPI struct {
	ctrl     *gomock.Controller
	recorder *MockrepoAPIMockRecorder
	isgomock struct{}
}

// MockrepoAPIMockRecorder is the mock recorder for MockrepoAPI.
type MockrepoAPIMockRecorder struct {
	mock *MockrepoAPI
}

// NewMockrepoAPI creates a new mock instance.
func NewMockrepoAPI(ctrl *gomock.Controller) *MockrepoAPI {
	mock := &MockrepoAPI{ctrl: ctrl}
	mock.recorder = &MockrepoAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrepoAPI) EXPECT() *MockrepoAPIMockRecorder {
	return m.recorder
}

// joinSession mocks base method.
func (m *MockrepoAPI) joinSession(ctx context.Context, params joinParams) (Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "joinSession", ctx, params)
	ret0, _ := ret[0].(Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// joinSession indicates an expected call of joinSession.
func (mr *MockrepoAPIMockRecorder) joinSession(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "joinSession", reflect.TypeOf((*MockrepoAPI)(nil).joinSession), ctx, params)
}

// resolveActiveSessionForJoinCode mocks base method.
func (m *MockrepoAPI) resolveActiveSessionForJoinCode(ctx context.Context, joinCode uint) (*joinCodeResolution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "resolveActiveSessionForJoinCode", ctx, joinCode)
	ret0, _ := ret[0].(*joinCodeResolution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// resolveActiveSessionForJoinCode indicates an expected call of resolveActiveSessionForJoinCode.
func (mr *MockrepoAPIMockRecorder) resolveActiveSessionForJoinCode(ctx, joinCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "resolveActiveSessionForJoinCode", reflect.TypeOf((*MockrepoAPI)(nil).resolveActiveSessionForJoinCode), ctx, joinCode)
}

// MockgameDefinitionResolver is a mock of gameDefinitionResolver interface.
type MockgameDefinitionResolver struct {
	ctrl     *gomock.Controller
	recorder *MockgameDefinitionResolverMockRecorder
	isgomock struct{}
}

// MockgameDefinitionResolverMockRecorder is the mock recorder for MockgameDefinitionResolver.
type MockgameDefinitionResolverMockRecorder struct {
	mock *MockgameDefinitionResolver
}

// NewMockgameDefinitionResolver creates a new mock instance.
func NewMockgameDefinitionResolver(ctrl *gomock.Controller) *MockgameDefinitionResolver {
	mock := &MockgameDefinitionResolver{ctrl: ctrl}
	mock.recorder = &MockgameDefinitionResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgameDefinitionResolver) EXPECT() *MockgameDefinitionResolverMockRecorder {
	return m.recorder
}

// GetGameDefinition mocks base method.
func (m *MockgameDefinitionResolver) GetGameDefinition(ctx context.Context, gameDefinitionUUID string) (*program.Definition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameDefinition", ctx, gameDefinitionUUID)
	ret0, _ := ret[0].(*program.Definition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameDefinition indicates an expected call of GetGameDefinition.
func (mr *MockgameDefinitionResolverMockRecorder) GetGameDefinition(ctx, gameDefinitionUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameDefinition", reflect.TypeOf((*MockgameDefinitionResolver)(nil).GetGameDefinition), ctx, gameDefinitionUUID)
}
