// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/diegobermudez03/playhoot/game/usecases/checkvisibility (interfaces: repoAPI)
//
// Generated by this command:
//
//	mockgen -package=checkvisibility -destination=repo_mock_test.go . repoAPI
//

// Package checkvisibility is a generated GoMock package.
package checkvisibility

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockrepoAPI is a mock of repoAPI interface.
type MockrepoAPI struct {
	ctrl     *gomock.Controller
	recorder *MockrepoAPIMockRecorder
	isgomock struct{}
}

// MockrepoAPIMockRecorder is the mock recorder for MockrepoAPI.
type MockrepoAPIMockRecorder struct {
	mock *MockrepoAPI
}

// NewMockrepoAPI creates a new mock instance.
func NewMockrepoAPI(ctrl *gomock.Controller) *MockrepoAPI {
	mock := &MockrepoAPI{ctrl: ctrl}
	mock.recorder = &MockrepoAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrepoAPI) EXPECT() *MockrepoAPIMockRecorder {
	return m.recorder
}

// ResolveVisibility mocks base method.
func (m *MockrepoAPI) ResolveVisibility(ctx context.Context, gameUUID string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveVisibility", ctx, gameUUID)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveVisibility indicates an expected call of ResolveVisibility.
func (mr *MockrepoAPIMockRecorder) ResolveVisibility(ctx, gameUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveVisibility", reflect.TypeOf((*MockrepoAPI)(nil).ResolveVisibility), ctx, gameUUID)
}
