// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/diegobermudez03/playhoot/game/game/usecases/getgamedefinition (interfaces: repoAPI)
//
// Generated by this command:
//
//	mockgen -package=getgamedefinition -destination=repo_mock_test.go . repoAPI
//

// Package getgamedefinition is a generated GoMock package.
package getgamedefinition

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockrepoAPI is a mock of repoAPI interface.
type MockrepoAPI struct {
	ctrl     *gomock.Controller
	recorder *MockrepoAPIMockRecorder
	isgomock struct{}
}

// MockrepoAPIMockRecorder is the mock recorder for MockrepoAPI.
type MockrepoAPIMockRecorder struct {
	mock *MockrepoAPI
}

// NewMockrepoAPI creates a new mock instance.
func NewMockrepoAPI(ctrl *gomock.Controller) *MockrepoAPI {
	mock := &MockrepoAPI{ctrl: ctrl}
	mock.recorder = &MockrepoAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrepoAPI) EXPECT() *MockrepoAPIMockRecorder {
	return m.recorder
}

// getGameDefinitionByUUID mocks base method.
func (m *MockrepoAPI) getGameDefinitionByUUID(ctx context.Context, gameDefinitionUUID string) (*gameDefinitionRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getGameDefinitionByUUID", ctx, gameDefinitionUUID)
	ret0, _ := ret[0].(*gameDefinitionRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getGameDefinitionByUUID indicates an expected call of getGameDefinitionByUUID.
func (mr *MockrepoAPIMockRecorder) getGameDefinitionByUUID(ctx, gameDefinitionUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getGameDefinitionByUUID", reflect.TypeOf((*MockrepoAPI)(nil).getGameDefinitionByUUID), ctx, gameDefinitionUUID)
}
